# Generated by Django 4.2.9 on 2024-04-25 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
        ('projects', '0001_initial'),
        ('ubication', '0001_initial'),
        ('tempo_extend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAfectacionesSociales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Tipo Afectación Social',
                'verbose_name_plural': 'Tipos Afectaciones Sociales',
                'db_table': 'cat_tipo_afectaciones_sociales',
            },
        ),
        migrations.CreateModel(
            name='AfectacionesSociales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_as', models.TextField()),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.nota')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.proyecto')),
                ('temporalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tempo_extend.temporalidad')),
                ('tipo_as', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_impact.tipoafectacionessociales')),
                ('ubicaciones', models.ManyToManyField(db_table='ocs.as_to_ubicaciones', to='ubication.ubicacion')),
            ],
            options={
                'verbose_name': 'Afectación Social',
                'verbose_name_plural': 'Afectaciones Sociales',
                'db_table': 'afectaciones_sociales',
            },
        ),
    ]
