# Generated by Django 4.2.9 on 2024-04-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_nota', models.IntegerField()),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('nombre_medio', models.CharField(max_length=100)),
                ('pagina_medio', models.CharField(max_length=100)),
                ('vinculo', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('fecha_captura', models.DateField()),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'db_table': 'notas',
            },
        ),
        migrations.CreateModel(
            name='RegistroNotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('datum', models.JSONField()),
                ('status', models.CharField(default='inprogress', max_length=100)),
                ('last_edit', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registro Nota',
                'verbose_name_plural': 'Registros Notas',
                'db_table': 'registro_notas',
            },
        ),
    ]
