# Generated by Django 4.2.9 on 2024-04-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionMujerVictima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Condición Mujer Víctima',
                'verbose_name_plural': 'Condiciones Mujer Víctima',
                'db_table': 'cat_condicion_mujer_victima',
            },
        ),
        migrations.CreateModel(
            name='SectorSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Sector Social',
                'verbose_name_plural': 'Sectores Sociales',
                'db_table': 'cat_sector_social',
            },
        ),
    ]
