# Generated by Django 4.2.9 on 2024-04-25 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
        ('ubication', '0001_initial'),
        ('projects', '0001_initial'),
        ('tempo_extend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaOrganizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Forma Organización',
                'verbose_name_plural': 'Formas Organización',
                'db_table': 'cat_forma_organizacion',
            },
        ),
        migrations.CreateModel(
            name='Mujer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Mujer',
                'verbose_name_plural': 'Mujeres',
                'db_table': 'cat_mujer',
            },
        ),
        migrations.CreateModel(
            name='PoblacionAfectada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Población Afectada',
                'verbose_name_plural': 'Poblaciones Afectadas',
                'db_table': 'cat_poblacion_afectada',
            },
        ),
        migrations.CreateModel(
            name='SubpoblacionAfectada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_subpoblacion_af', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Subpoblación Afectada',
                'verbose_name_plural': 'Subpoblaciones Afectadas',
                'db_table': 'cat_subpoblacion_afectada',
            },
        ),
        migrations.CreateModel(
            name='PoblacionesAfectadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('interes', models.TextField()),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.nota')),
                ('poblacion_afectada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors.poblacionafectada')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.proyecto')),
                ('subpoblacion_afectada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors.subpoblacionafectada')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubication.ubicacion')),
            ],
            options={
                'verbose_name': 'Población Afectada',
                'verbose_name_plural': 'Poblaciones Afectadas',
                'db_table': 'poblaciones_afectadas',
            },
        ),
        migrations.CreateModel(
            name='Opositor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('is_indigena', models.BooleanField()),
                ('pueblo_indigena', models.CharField(max_length=100)),
                ('is_campesino_or_comunero_or_ejidatario', models.BooleanField()),
                ('is_trabajador_empresa', models.BooleanField()),
                ('otros_opositores', models.TextField()),
                ('is_habitante_zona', models.BooleanField()),
                ('forma_organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors.formaorganizacion')),
                ('mujer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors.mujer')),
                ('notas', models.ManyToManyField(db_table='ocs.opositores_to_notas', to='notes.nota')),
                ('proyectos', models.ManyToManyField(db_table='ocs.opositores_to_proyecto', to='projects.proyecto')),
                ('ubicaciones', models.ManyToManyField(db_table='ocs.opositores_to_ubicaciones', to='ubication.ubicacion')),
            ],
            options={
                'verbose_name': 'Opositor',
                'verbose_name_plural': 'Opositores',
                'db_table': 'opositores',
            },
        ),
        migrations.CreateModel(
            name='InteresesPoblacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interes', models.TextField()),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.nota')),
                ('poblacion_afectada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors.poblacionafectada')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.proyecto')),
            ],
            options={
                'verbose_name': 'Interés Población',
                'verbose_name_plural': 'Intereses Poblaciones',
                'db_table': 'intereses_poblacion',
            },
        ),
        migrations.CreateModel(
            name='InteresesOpositores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interes', models.TextField()),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.nota')),
                ('opositor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors.opositor')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.proyecto')),
            ],
            options={
                'verbose_name': 'Interés Opositor',
                'verbose_name_plural': 'Intereses Opositores',
                'db_table': 'intereses_opositores',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituciones_a_favor_proyecto', models.TextField()),
                ('instituciones_mediadoras', models.TextField()),
                ('instituciones_atienden_reclamos', models.TextField()),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.nota')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.proyecto')),
                ('temporalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tempo_extend.temporalidad')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('matriz', models.TextField()),
                ('filial', models.TextField()),
                ('directores', models.TextField()),
                ('inversionistas', models.TextField()),
                ('nacionalidad', models.CharField(max_length=100)),
                ('is_capital_publico', models.BooleanField()),
                ('is_cotiza_bolsa', models.BooleanField()),
                ('interes', models.TextField()),
                ('is_activo', models.BooleanField()),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.nota')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.proyecto')),
            ],
            options={
                'verbose_name': 'Capital',
                'verbose_name_plural': 'Capitales',
                'db_table': 'capital',
            },
        ),
    ]
