generic_responsable_no_estatal_desc = [
    "100 acarreados",
    "Civiles",
    "Civiles armados",
    "Comando armado",
    "Comisariado Ejidal",
    "Crimen orgaizado",
    "Crimen organizado",
    "Delincuencia organizada",
    "Delincuentes",
    "Empleados de la minera",
    "Empresa constructora",
    "Empresa encargada de la mina",
    "Empresario",
    "Empresarios de materiales",
    "Encapuchados",
    "Grupo armado",
    "Grupo armado ",
    "Grupo de choque",
    "Grupo de hombres armados",
    "Grupo de personas infiltradas",
    "Grupo delicuencial",
    "Grupo delincuencial ",
    "Grupos criminales",
    "Grupos criminales",
    "Grupos de choque",
    "Hombres armados",
    "Iniciativa privada",
    "Inversionistas",
    "Narcotráfico",
    "Notario público",
    "Paramilitares",
    "Personal armado",
    "Personal que trabajan para la inmobiliaria ",
    "Personas armadas",
    "Pistoleros",
    "Porros",
    "Presuntos agentes de la empresa",
    "Sicarios",
    "Sujetos armados",
    "Talamontes",
    "Talamontes ",
    "Talamontes y crimen organizado",
    "constructoras",
]
