# Generated by Django 4.2.9 on 2024-06-25 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('work_flux', '0001_initial'),
        ('space_time', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filled', models.BooleanField(default=False)),
                ('date_filled', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mención de proyecto en nota',
                'verbose_name_plural': 'Menciones de proyectos en notas',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_news', models.BooleanField(blank=True, null=True)),
                ('main_url', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Fuente de información',
                'verbose_name_plural': 'Fuentes de información',
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('interval', models.DurationField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('type_temporalidad', models.CharField(blank=True, max_length=20, null=True)),
                ('mention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.mention')),
                ('status_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space_time.statusproject')),
            ],
            options={
                'verbose_name': 'Historial de estatus de proyecto',
                'verbose_name_plural': 'Historiales de estatus de proyectos',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_id_ref', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('old_id', models.IntegerField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('section', models.CharField(blank=True, max_length=120, null=True)),
                ('pages', models.CharField(blank=True, max_length=80, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('date', models.DateField()),
                ('capture_date', models.DateField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.source', verbose_name='Fuente de información')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
        migrations.AddField(
            model_name='mention',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.note'),
        ),
        migrations.AddField(
            model_name='mention',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.AddField(
            model_name='mention',
            name='status_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol'),
        ),
    ]
