# Generated by Django 4.2.9 on 2024-04-29 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('space_time', '0001_initial'),
        ('work_flux', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_news', models.BooleanField(blank=True, null=True)),
                ('main_url', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Fuente de información',
                'verbose_name_plural': 'Fuentes de información',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('old_id', models.IntegerField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('date', models.DateField()),
                ('capture_date', models.DateField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.source')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filled', models.BooleanField(default=False)),
                ('date_filled', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.note')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('status_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space_time.statusproject')),
                ('status_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol')),
            ],
            options={
                'verbose_name': 'Mención de proyecto en nota',
                'verbose_name_plural': 'Menciones de proyectos en notas',
            },
        ),
    ]
