# Generated by Django 4.2.9 on 2024-05-03 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='pages',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='section',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.source', verbose_name='Fuente de información'),
        ),
    ]
