# Generated by Django 4.2.9 on 2025-01-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='capture_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
