# Generated by Django 4.2.9 on 2024-06-28 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_projectlocation_location_and_more'),
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mention',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='source.note'),
        ),
        migrations.AlterField(
            model_name='mention',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='project.project'),
        ),
    ]
