# Generated by Django 4.2.9 on 2025-01-28 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='screenshot',
        ),
    ]
