# Generated by Django 4.2.9 on 2024-11-26 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_statusproject_alter_project_status_project'),
        ('source', '0002_alter_note_capture_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statushistory',
            name='status_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.statusproject'),
        ),
    ]
