# Generated by Django 4.2.9 on 2025-01-20 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_alter_note_capture_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='source.source', verbose_name='Fuente de información'),
        ),
    ]
