# Generated by Django 4.2.9 on 2024-09-20 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_alter_mention_note_alter_mention_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statushistory',
            name='mention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='source.mention'),
        ),
    ]
