# Generated by Django 4.2.9 on 2025-02-11 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_remove_note_screenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('scraped_date', models.DateField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_records', to='source.source')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('section', models.CharField(blank=True, max_length=120, null=True)),
                ('url', models.CharField(max_length=255)),
                ('imgs', models.TextField(blank=True, null=True)),
                ('basic_content', models.TextField(blank=True, null=True)),
                ('scraped_date', models.DateField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('preclasification', models.CharField(blank=True, choices=[('invalido', 'Invalido'), ('válido', 'Valido'), ('podría ser', 'Podría ser')], max_length=10, null=True)),
                ('autor', models.CharField(blank=True, max_length=255, null=True)),
                ('htmml_content', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, null=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('criteria', models.JSONField(blank=True, null=True)),
                ('scraped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='source.scrapedrecord')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='source.source')),
            ],
            options={
                'unique_together': {('uid', 'source')},
            },
        ),
    ]
