# Generated by Django 4.2.9 on 2024-05-03 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space_time', '0001_initial'),
        ('source', '0002_note_pages_note_section_alter_note_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mention',
            name='status_project',
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('interval', models.DurationField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('type_temporalidad', models.CharField(blank=True, max_length=20, null=True)),
                ('mention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.mention')),
                ('status_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space_time.statusproject')),
            ],
            options={
                'verbose_name': 'Historial de estatus de proyecto',
                'verbose_name_plural': 'Historiales de estatus de proyectos',
            },
        ),
    ]
