# Generated by Django 4.2.9 on 2025-02-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0003_scrapedrecord_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='preclasification',
            field=models.CharField(blank=True, choices=[('inválido', 'Invalido'), ('válido', 'Valido'), ('podría ser', 'Podría ser')], max_length=10, null=True),
        ),
    ]
