# Generated by Django 4.2.9 on 2024-05-03 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space_time', '0001_initial'),
        ('source', '0003_remove_mention_status_project_statushistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statushistory',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='status_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space_time.statusproject'),
        ),
    ]
