# Generated by Django 4.2.9 on 2024-09-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0004_note_editor_note_reviewer_note_status_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mention',
            name='status_register',
        ),
        migrations.AddField(
            model_name='note',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
