# Generated by Django 4.2.9 on 2025-02-11 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0004_alter_article_preclasification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='htmml_content',
            new_name='html_content',
        ),
    ]
