# Generated by Django 4.2.9 on 2024-10-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0005_remove_mention_status_register_note_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='order',
            field=models.SmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='source',
            name='is_news',
            field=models.BooleanField(default=True, verbose_name='Es una fuente de noticias'),
        ),
    ]
