# Generated by Django 4.2.9 on 2025-02-14 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0005_rename_htmml_content_article_html_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapedrecord',
            old_name='date_from',
            new_name='from_date',
        ),
        migrations.RenameField(
            model_name='scrapedrecord',
            old_name='date_to',
            new_name='to_date',
        ),
        migrations.AddField(
            model_name='article',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='source.note'),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='errors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='preclassification',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='status',
            field=models.CharField(blank=True, choices=[('get_sections', 'Traer secciones'), ('record_articles', 'Guardar artículos'), ('preclassify', 'Preclasificar'), ('criteria', 'Criterios'), ('completed', 'Completado'), ('failed', 'Fallido')], max_length=20, null=True),
        ),
    ]
