# Generated by Django 4.2.9 on 2025-02-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0006_rename_date_from_scrapedrecord_from_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='preclasification',
            field=models.CharField(blank=True, choices=[('invalid', 'Invalido'), ('valid', 'Valido'), ('maybe', 'Podría ser')], max_length=10, null=True),
        ),
    ]
