# Generated by Django 4.2.9 on 2024-10-11 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0006_source_order_alter_source_is_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['order'], 'verbose_name': 'Fuente de información', 'verbose_name_plural': 'Fuentes de información'},
        ),
    ]
