# Generated by Django 4.2.9 on 2025-02-16 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0007_alter_article_preclasification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='preclasification',
            new_name='preclassification',
        ),
    ]
