# Generated by Django 4.2.9 on 2025-02-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0008_rename_preclasification_article_preclassification'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='request_openai',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='preclassification',
            field=models.CharField(blank=True, choices=[('invalid', 'Invalido'), ('valid', 'Valido'), ('maybe', 'Podría ser'), ('indirect', 'Indirecto')], max_length=10, null=True),
        ),
    ]
