# Generated by Django 4.2.9 on 2024-10-24 10:14

from django.db import migrations, models
import source.models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0008_notefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='slug_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notefile',
            name='file',
            field=models.FileField(upload_to=source.models.upload_to_note_file),
        ),
    ]
