# Generated by Django 4.2.9 on 2024-10-24 10:29

from django.db import migrations, models
import source.models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0009_note_slug_title_alter_notefile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notefile',
            name='file',
            field=models.FileField(max_length=255, upload_to=source.models.upload_to_note_file),
        ),
    ]
