# Generated by Django 4.2.9 on 2025-02-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0009_article_request_openai_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='request_openai',
            new_name='request_criteria_openai',
        ),
        migrations.AddField(
            model_name='article',
            name='request_pre_openai',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
