# Generated by Django 4.2.9 on 2025-02-18 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0010_rename_request_openai_article_request_criteria_openai_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualifySchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ia_model', models.CharField(max_length=255)),
                ('prompt_version', models.CharField(choices=[('preclassify_v1', 'Preclasificación v1'), ('preclassify_v2', 'Preclasificación v2'), ('criteria_v1', 'Criterios v1'), ('criteria_v2', 'Criterios v2')], max_length=20)),
                ('batch_size', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Esquema de calificación',
                'verbose_name_plural': 'Esquemas de calificación',
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='request_criteria_openai',
        ),
        migrations.RemoveField(
            model_name='article',
            name='request_pre_openai',
        ),
        migrations.AddField(
            model_name='article',
            name='is_selected',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='preclassification',
            field=models.CharField(blank=True, choices=[('invalid', 'Invalido'), ('valid', 'Valido'), ('maybe', 'Podría ser'), ('indirect', 'Indirecto'), ('unknown', 'Desconocido')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='ArticleQualify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_selected', models.BooleanField(blank=True, null=True)),
                ('change_value', models.CharField(blank=True, choices=[('minus', 'Erróneamente excluido'), ('plus', 'Erróneamente incluido'), ('selected', 'Incluido correctamente'), ('not_selected', 'Excluido correctamente')], max_length=20, null=True)),
                ('request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='source.article')),
                ('qualify_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='source.qualifyschema')),
            ],
            options={
                'verbose_name': 'Calificación de artículo',
                'verbose_name_plural': 'Calificaciones de artículos',
            },
        ),
    ]
