# Generated by Django 4.2.9 on 2024-10-29 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0010_alter_notefile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mention',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='note',
            name='comments',
        ),
    ]
