# Generated by Django 4.2.9 on 2024-10-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0011_remove_mention_comments_remove_note_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='mention',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
