# Generated by Django 4.2.9 on 2025-02-18 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0011_qualifyschema_remove_article_request_criteria_openai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualifyschema',
            name='scraped_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to='source.scrapedrecord'),
        ),
    ]
