# Generated by Django 4.2.9 on 2025-02-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0012_qualifyschema_scraped_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='certainty_degree',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlequalify',
            name='certainty_degree',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlequalify',
            name='criteria',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
