# Generated by Django 4.2.9 on 2025-02-18 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0011_alter_article_title'),
        ('source', '0013_article_certainty_degree_and_more'),
    ]

    operations = [
    ]
