# Generated by Django 4.2.9 on 2025-07-19 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0014_merge_20250218_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='preclassification',
        ),
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='preclassification',
        ),
    ]
