# Generated by Django 4.2.9 on 2025-07-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0015_remove_article_preclassification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='paragraphs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
