# Generated by Django 4.2.9 on 2025-07-21 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0016_article_paragraphs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-scraped_date', '-published_date'], 'verbose_name': 'Artículo', 'verbose_name_plural': 'Artículos'},
        ),
        migrations.AlterModelOptions(
            name='scrapedrecord',
            options={'ordering': ['from_date'], 'verbose_name': 'Bloque de scrapeo', 'verbose_name_plural': 'Bloques de scrapeo'},
        ),
    ]
