# Generated by Django 4.2.9 on 2025-07-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0017_alter_article_options_alter_scrapedrecord_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subtitle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
