# Generated by Django 4.2.9 on 2025-08-02 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0018_article_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscardedReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.SmallIntegerField(default=5)),
            ],
            options={
                'verbose_name': 'Razón de descarte',
                'verbose_name_plural': 'Razones de descarte',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_date', '-certainty_degree'], 'verbose_name': 'Artículo', 'verbose_name_plural': 'Artículos'},
        ),
        migrations.AddField(
            model_name='article',
            name='other_discarded_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='discarded_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='source.discardedreason'),
        ),
    ]
