# Generated by Django 4.2.9 on 2025-08-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0019_discardedreason_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='subtitle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
