# Generated by Django 4.2.9 on 2025-08-11 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0020_note_subtitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-certainty_degree', '-published_date'], 'verbose_name': 'Artículo', 'verbose_name_plural': 'Artículos'},
        ),
        migrations.AlterModelOptions(
            name='scrapedrecord',
            options={'ordering': ['-from_date'], 'verbose_name': 'Bloque de scrapeo', 'verbose_name_plural': 'Bloques de scrapeo'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='autor',
            new_name='author',
        ),
    ]
