# Generated by Django 4.2.9 on 2025-09-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0021_alter_article_options_alter_scrapedrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-certainty_degree', '-published_date'], 'verbose_name': 'Pre-Nota', 'verbose_name_plural': 'Pre-Notas'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Nota Final', 'verbose_name_plural': 'Notas Finales'},
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='date_started',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='certainty_degree',
            field=models.IntegerField(blank=True, help_text='Debe superar 100 para ser considerado', null=True),
        ),
    ]
