# Generated by Django 4.2.9 on 2025-09-03 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def add_saved_users(apps, schema_editor):
    Note = apps.get_model('source', 'Note')
    for note in Note.objects.all():
        if note.editor:
            note.editors.add(note.editor)
        if note.reviewer:
            note.reviewers.add(note.reviewer)
    # No need to call note.save() as ManyToManyField changes are saved immediately


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('source', '0022_alter_article_options_alter_note_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='reviewers',
            field=models.ManyToManyField(blank=True, related_name='reviewers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editors2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewers2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(add_saved_users, reverse_code=migrations.RunPython.noop),
    ]
