# Generated by Django 5.2.6 on 2025-11-28 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0024_scrapedrecord_date_ended_scrapedrecord_user'),
        ('work_flux', '0003_alter_statuscontrol_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discardedreason',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Razón de descarte', 'verbose_name_plural': 'Razones de descarte'},
        ),
        migrations.RenameField(
            model_name='scrapedrecord',
            old_name='date_ended',
            new_name='date_end',
        ),
        migrations.RenameField(
            model_name='scrapedrecord',
            old_name='date_started',
            new_name='date_start',
        ),
        migrations.AddField(
            model_name='article',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='second_certainty_degree',
            field=models.IntegerField(blank=True, help_text='Debe superar 100 para ser considerado', null=True, verbose_name='Grado de certeza (deep)'),
        ),
        migrations.AddField(
            model_name='article',
            name='second_criteria',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='status_validation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol'),
        ),
        migrations.AddField(
            model_name='discardedreason',
            name='is_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='certainty_degree',
            field=models.IntegerField(blank=True, help_text='Debe superar 100 para ser considerado', null=True, verbose_name='Grado de certeza'),
        ),
    ]
