# Generated by Django 5.2.6 on 2025-11-28 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0025_alter_discardedreason_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='status_validation',
            new_name='status_retro',
        ),
    ]
