# Generated by Django 5.2.6 on 2025-11-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0026_rename_status_validation_article_status_retro'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedrecord',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
