# Generated by Django 5.2.6 on 2026-01-09 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project_editors'),
        ('source', '0027_scrapedrecord_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='errors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='status_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_histories', to='project.statusproject'),
        ),
    ]
