# Generated by Django 5.2.6 on 2026-01-15 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project_editors'),
        ('source', '0028_article_errors_alter_statushistory_status_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': [models.OrderBy(models.F('second_certainty_degree'), descending=True, nulls_last=True), '-certainty_degree', '-published_date'], 'verbose_name': 'Pre-Nota', 'verbose_name_plural': 'Pre-Notas'},
        ),
        migrations.RemoveField(
            model_name='mention',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='statushistory',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='statushistory',
            name='type_temporalidad',
        ),
        migrations.AddField(
            model_name='mention',
            name='discarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mention',
            name='pre_project',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='pre_mentions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mention',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='project.project'),
        ),
    ]
