# Generated by Django 5.2.6 on 2026-01-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0029_alter_article_options_remove_mention_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pre_capture',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
