# Generated by Django 5.2.6 on 2026-01-28 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project_editors'),
        ('source', '0030_article_pre_capture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mention',
            name='discarded',
        ),
        migrations.RemoveField(
            model_name='mention',
            name='pre_project',
        ),
        migrations.AddField(
            model_name='note',
            name='frozen_pre_capture',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mention',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='project.project'),
        ),
    ]
