# Generated by Django 5.2.6 on 2026-02-05 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0031_remove_mention_discarded_remove_mention_pre_project_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statushistory',
            options={'verbose_name': 'Cambios de estatus', 'verbose_name_plural': 'Cambios de status'},
        ),
    ]
