# Generated by Django 5.2.6 on 2026-02-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0032_alter_statushistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pages',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
