# Generated by Django 5.2.6 on 2026-03-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0033_article_pages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': [models.OrderBy(models.F('second_certainty_degree'), descending=True, nulls_last=True), '-certainty_degree', '-published_date'], 'verbose_name': 'Pre-Nota (Artículo)', 'verbose_name_plural': 'Pre-Notas (Artículos)'},
        ),
    ]
