# Generated by Django 5.2.6 on 2026-04-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0034_alter_article_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressReaderSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bearer_token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_validated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sesión de PressReader',
                'verbose_name_plural': 'Sesiones de PressReader',
            },
        ),
    ]
