# Generated by Django 5.2.15 on 2026-07-21 20:05

import core.storages
import source.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0035_pressreadersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notefile',
            name='file',
            field=models.FileField(max_length=255, storage=core.storages.select_docs_storage, upload_to=source.models.upload_to_note_file),
        ),
    ]
