# Generated by Django 5.2.15 on 2026-08-02 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0036_alter_notefile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='status',
        ),
    ]
