# Generated by Django 4.2.9 on 2024-06-25 10:08

import actor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classify', '0001_initial'),
        ('work_flux', '0001_initial'),
        ('source', '0001_initial'),
        ('space_time', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('official_name', models.CharField(blank=True, max_length=255, null=True)),
                ('std_name', models.CharField(blank=True, max_length=255, null=True)),
                ('alternative_names', models.JSONField(blank=True, default=actor.models.default_list, null=True)),
                ('is_incomplete', models.BooleanField(default=False)),
                ('is_name_created', models.BooleanField(default=False)),
                ('is_only_related', models.BooleanField(blank=True, null=True)),
                ('sector_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del sector (opcional)')),
                ('geo_reach', models.CharField(blank=True, choices=[('local', 'Local'), ('regional', 'Regional'), ('national', 'Nacional'), ('international', 'Internacional'), ('global', 'Global')], max_length=15, null=True)),
                ('capital_extension', models.JSONField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('man', 'Hombre'), ('woman', 'Mujer')], max_length=10, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('capital_id_ref', models.IntegerField(blank=True, null=True)),
                ('belongs', models.ManyToManyField(blank=True, to='classify.belong')),
                ('countries', models.ManyToManyField(blank=True, to='space_time.country')),
                ('indigenous_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classify.indigenousgroup')),
                ('parent_actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actor.actor')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classify.sector')),
                ('status_validation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol')),
            ],
            options={
                'verbose_name': 'Actor',
                'verbose_name_plural': 'Actores',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actor.actor')),
                ('mention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.mention')),
                ('participant_types', models.ManyToManyField(blank=True, to='classify.participanttype')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
            },
        ),
        migrations.CreateModel(
            name='OriginReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_model', models.CharField(choices=[('Capital', 'Capital'), ('Estado', 'Estado'), ('Opositores', 'Opositores'), ('Poblacione', 'PoblacionesAfectadas'), ('GruposApoyo', 'GruposApoyo')], max_length=20)),
                ('field_name', models.CharField(blank=True, max_length=255, null=True)),
                ('origin_id', models.IntegerField()),
                ('actor_created', models.BooleanField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actor.actor')),
            ],
            options={
                'verbose_name': 'Referencia de Origen',
                'verbose_name_plural': 'Referencias de Origen',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('director', 'Director'), ('investor', 'Inversionista'), ('chief_executive', 'Director Ejecutivo'), ('other', 'Otro directivo'), ('member', 'Integrante')], default='member', max_length=20)),
                ('actor_collective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_collective', to='actor.actor')),
                ('actor_individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_individual', to='actor.actor')),
            ],
            options={
                'verbose_name': 'Persona integrante de actor colectivo',
                'verbose_name_plural': 'Personas integrantes de actor colectivo',
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('interest_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classify.interesttype')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actor.participant')),
            ],
            options={
                'verbose_name': 'Interés',
                'verbose_name_plural': 'Intereses',
            },
        ),
    ]
