# Generated by Django 4.2.9 on 2024-04-30 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('space_time', '0002_alter_country_table'),
        ('source', '0002_alter_note_author_alter_note_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_incomplete', models.BooleanField(default=False)),
                ('is_name_created', models.BooleanField(default=False)),
                ('is_only_related', models.BooleanField(default=False)),
                ('sector_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del sector (opcional)')),
                ('geo_reach', models.CharField(blank=True, choices=[('local', 'Local'), ('regional', 'Regional'), ('national', 'Nacional'), ('international', 'Internacional'), ('global', 'Global')], max_length=15, null=True)),
                ('capital_extension', models.JSONField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('man', 'Hombre'), ('woman', 'Mujer')], max_length=10, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Actor',
                'verbose_name_plural': 'Actores',
            },
        ),
        migrations.CreateModel(
            name='Belong',
            fields=[
                ('key_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Vulnerabilidad',
                'verbose_name_plural': 'Vulnerabilidades',
            },
        ),
        migrations.CreateModel(
            name='CapitalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Capital',
                'verbose_name_plural': 'Tipos de Capital',
            },
        ),
        migrations.CreateModel(
            name='IndigenousGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Grupo Indígena',
                'verbose_name_plural': 'Grupos Indígenas',
            },
        ),
        migrations.CreateModel(
            name='InterestGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.CharField(choices=[('denuncia', 'Denuncia'), ('demanda', 'Demanda'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Agrupador de tipos de interés',
                'verbose_name_plural': 'Agrupadores de tipos de interés',
            },
        ),
        migrations.CreateModel(
            name='ParticipantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[('undefined', 'No definido'), ('maybe_support', 'Posiblemente a favor'), ('support', 'A favor'), ('oppose', 'En contra'), ('neutral', 'Neutral'), ('other', 'Otro')], default='undefined', max_length=14)),
                ('required_interests', models.BooleanField(default=True, verbose_name='Se requerirá que se agreguen intereses')),
                ('is_temporal', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Participación en Proyecto',
                'verbose_name_plural': 'Tipos de Participación en Proyecto',
            },
        ),
        migrations.CreateModel(
            name='SectorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_collective', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Grupo Sectorial',
                'verbose_name_plural': 'Grupos Sectoriales',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('needs_name', models.BooleanField(default=False)),
                ('has_belongs', models.BooleanField(default=True)),
                ('common_belongs', models.ManyToManyField(blank=True, to='actor.belong')),
                ('common_participant_types', models.ManyToManyField(blank=True, to='actor.participanttype')),
                ('sector_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actor.sectorgroup')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actor.actor')),
                ('mention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.mention')),
                ('participant_types', models.ManyToManyField(blank=True, to='actor.participanttype')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
            },
        ),
        migrations.CreateModel(
            name='InterestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actor.interestgroup')),
            ],
            options={
                'verbose_name': 'Tipo de Interés',
                'verbose_name_plural': 'Tipos de Interés',
            },
        ),
        migrations.AddField(
            model_name='interestgroup',
            name='participant_types',
            field=models.ManyToManyField(blank=True, to='actor.participanttype'),
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('interest_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actor.interesttype')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actor.participant')),
            ],
            options={
                'verbose_name': 'Interés',
                'verbose_name_plural': 'Intereses',
            },
        ),
        migrations.AddField(
            model_name='actor',
            name='belongs',
            field=models.ManyToManyField(blank=True, to='actor.belong'),
        ),
        migrations.AddField(
            model_name='actor',
            name='capital_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actor.capitaltype'),
        ),
        migrations.AddField(
            model_name='actor',
            name='countries',
            field=models.ManyToManyField(blank=True, to='space_time.country'),
        ),
        migrations.AddField(
            model_name='actor',
            name='indigenous_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actor.indigenousgroup'),
        ),
        migrations.AddField(
            model_name='actor',
            name='parent_actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actor.actor'),
        ),
        migrations.AddField(
            model_name='actor',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actor.sector'),
        ),
    ]
