# Generated by Django 4.2.9 on 2024-05-16 00:17

import actor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work_flux', '0001_initial'),
        ('source', '0001_initial'),
        ('space_time', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('official_name', models.CharField(blank=True, max_length=255, null=True)),
                ('std_name', models.CharField(blank=True, max_length=255, null=True)),
                ('alternative_names', models.JSONField(blank=True, default=actor.models.default_list, null=True)),
                ('is_incomplete', models.BooleanField(default=False)),
                ('is_name_created', models.BooleanField(default=False)),
                ('is_only_related', models.BooleanField(blank=True, null=True)),
                ('sector_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del sector (opcional)')),
                ('geo_reach', models.CharField(blank=True, choices=[('local', 'Local'), ('regional', 'Regional'), ('national', 'Nacional'), ('international', 'Internacional'), ('global', 'Global')], max_length=15, null=True)),
                ('capital_extension', models.JSONField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('man', 'Hombre'), ('woman', 'Mujer')], max_length=10, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('capital_id_ref', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Actor',
                'verbose_name_plural': 'Actores',
            },
        ),
        migrations.CreateModel(
            name='Belong',
            fields=[
                ('key_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Vulnerabilidad',
                'verbose_name_plural': 'Vulnerabilidades',
            },
        ),
        migrations.CreateModel(
            name='IndigenousGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Grupo Indígena',
                'verbose_name_plural': 'Grupos Indígenas',
            },
        ),
        migrations.CreateModel(
            name='InterestGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.CharField(choices=[('denuncia', 'Denuncia'), ('demanda', 'Demanda'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Agrupador de tipos de interés',
                'verbose_name_plural': 'Agrupadores de tipos de interés',
            },
        ),
        migrations.CreateModel(
            name='ParticipantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[('undefined', 'No definido'), ('maybe_support', 'Posiblemente a favor'), ('support', 'A favor'), ('oppose', 'En contra'), ('neutral', 'Neutral'), ('other', 'Otro')], default='undefined', max_length=14)),
                ('required_interests', models.BooleanField(default=True, verbose_name='Se requerirá que se agreguen intereses')),
                ('description', models.TextField(blank=True, null=True)),
                ('status_validation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol')),
            ],
            options={
                'verbose_name': 'Tipo de Participación en Proyecto',
                'verbose_name_plural': 'Tipos de Participación en Proyecto',
            },
        ),
        migrations.CreateModel(
            name='SectorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_collective', models.BooleanField(blank=True, null=True)),
                ('has_belongs', models.BooleanField(default=True)),
                ('capital_type', models.CharField(blank=True, choices=[('public', 'Público'), ('private', 'Privado'), ('mixed', 'Mixto'), ('conflict', 'Conflicto')], max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Grupo Sectorial',
                'verbose_name_plural': 'Grupos Sectoriales',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('needs_name', models.BooleanField(default=False)),
                ('common_belongs', models.ManyToManyField(blank=True, to='actor.belong')),
                ('common_participant_types', models.ManyToManyField(blank=True, to='actor.participanttype')),
                ('sector_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actor.sectorgroup')),
                ('status_validation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actor.actor')),
                ('mention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.mention')),
                ('participant_types', models.ManyToManyField(blank=True, to='actor.participanttype')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
            },
        ),
        migrations.CreateModel(
            name='OriginReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_model', models.CharField(choices=[('Capital', 'Capital'), ('Estado', 'Estado'), ('Opositores', 'Opositores'), ('Poblacione', 'PoblacionesAfectadas'), ('GruposApoyo', 'GruposApoyo')], max_length=20)),
                ('field_name', models.CharField(blank=True, max_length=255, null=True)),
                ('origin_id', models.IntegerField()),
                ('actor_created', models.BooleanField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actor.actor')),
            ],
            options={
                'verbose_name': 'Referencia de Origen',
                'verbose_name_plural': 'Referencias de Origen',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('director', 'Director'), ('investor', 'Inversionista'), ('chief_executive', 'Director Ejecutivo'), ('other', 'Otro directivo'), ('member', 'Integrante')], default='member', max_length=20)),
                ('actor_collective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_collective', to='actor.actor')),
                ('actor_individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_individual', to='actor.actor')),
            ],
            options={
                'verbose_name': 'Persona integrante de actor colectivo',
                'verbose_name_plural': 'Personas integrantes de actor colectivo',
            },
        ),
        migrations.CreateModel(
            name='InterestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actor.interestgroup')),
            ],
            options={
                'verbose_name': 'Tipo de Interés',
                'verbose_name_plural': 'Tipos de Interés',
            },
        ),
        migrations.AddField(
            model_name='interestgroup',
            name='participant_types',
            field=models.ManyToManyField(blank=True, to='actor.participanttype'),
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('interest_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actor.interesttype')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actor.participant')),
            ],
            options={
                'verbose_name': 'Interés',
                'verbose_name_plural': 'Intereses',
            },
        ),
        migrations.AddField(
            model_name='actor',
            name='belongs',
            field=models.ManyToManyField(blank=True, to='actor.belong'),
        ),
        migrations.AddField(
            model_name='actor',
            name='countries',
            field=models.ManyToManyField(blank=True, to='space_time.country'),
        ),
        migrations.AddField(
            model_name='actor',
            name='indigenous_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actor.indigenousgroup'),
        ),
        migrations.AddField(
            model_name='actor',
            name='parent_actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actor.actor'),
        ),
        migrations.AddField(
            model_name='actor',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actor.sector'),
        ),
        migrations.AddField(
            model_name='actor',
            name='status_validation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol'),
        ),
    ]
