# Generated by Django 4.2.9 on 2024-11-06 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work_flux', '0001_initial'),
        ('actor', '0001_initial'),
        ('space_time', '0001_initial'),
        ('classify', '0001_initial'),
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='mention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='source.mention'),
        ),
        migrations.AddField(
            model_name='participant',
            name='participant_types',
            field=models.ManyToManyField(blank=True, to='classify.participanttype'),
        ),
        migrations.AddField(
            model_name='originreference',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_references', to='actor.actor'),
        ),
        migrations.AddField(
            model_name='member',
            name='actor_collective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_collective', to='actor.actor'),
        ),
        migrations.AddField(
            model_name='member',
            name='actor_individual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_individual', to='actor.actor'),
        ),
        migrations.AddField(
            model_name='interest',
            name='interest_subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='classify.interestsubtype'),
        ),
        migrations.AddField(
            model_name='interest',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='actor.participant'),
        ),
        migrations.AddField(
            model_name='actor',
            name='belongs',
            field=models.ManyToManyField(blank=True, to='classify.belong'),
        ),
        migrations.AddField(
            model_name='actor',
            name='countries',
            field=models.ManyToManyField(blank=True, to='space_time.country'),
        ),
        migrations.AddField(
            model_name='actor',
            name='indigenous_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='classify.indigenousgroup'),
        ),
        migrations.AddField(
            model_name='actor',
            name='others_parents',
            field=models.ManyToManyField(blank=True, to='actor.actor', verbose_name='Otros padres'),
        ),
        migrations.AddField(
            model_name='actor',
            name='parent_actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_actors', to='actor.actor', verbose_name='Actor padre'),
        ),
        migrations.AddField(
            model_name='actor',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classify.sector'),
        ),
        migrations.AddField(
            model_name='actor',
            name='status_validation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol'),
        ),
    ]
