# Generated by Django 4.2.9 on 2024-05-03 09:00

import actor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_flux', '0001_initial'),
        ('actor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='alternative_names',
            field=models.JSONField(blank=True, default=actor.models.default_list, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='official_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='status_validation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol'),
        ),
        migrations.AddField(
            model_name='actor',
            name='std_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='is_only_related',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
