# Generated by Django 4.2.9 on 2024-06-28 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
        ('actor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='actor.participant'),
        ),
        migrations.AlterField(
            model_name='originreference',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_references', to='actor.actor'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='actor.actor'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='mention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='source.mention'),
        ),
    ]
