# Generated by Django 4.2.9 on 2024-05-09 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0002_actor_alternative_names_actor_official_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_model', models.CharField(choices=[('Capital', 'Capital'), ('Estado', 'Estado'), ('Opositores', 'Opositores'), ('Poblacione', 'PoblacionesAfectadas'), ('GruposApoyo', 'GruposApoyo')], max_length=20)),
                ('origin_id', models.IntegerField()),
                ('actor_created', models.BooleanField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actor.actor')),
            ],
            options={
                'verbose_name': 'Referencia de Origen',
                'verbose_name_plural': 'Referencias de Origen',
            },
        ),
    ]
