# Generated by Django 4.2.9 on 2025-01-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='others_parents',
            field=models.ManyToManyField(blank=True, related_name='children_actors_others', to='actor.actor', verbose_name='Otros padres'),
        ),
    ]
