# Generated by Django 4.2.9 on 2024-09-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0002_alter_interest_participant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='others_parents',
            field=models.ManyToManyField(blank=True, to='actor.actor', verbose_name='Otros padres'),
        ),
    ]
