# Generated by Django 4.2.9 on 2024-05-11 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_flux', '0001_initial'),
        ('actor', '0003_originreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='capital_type',
        ),
        migrations.RemoveField(
            model_name='participanttype',
            name='is_temporal',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='has_belongs',
        ),
        migrations.AddField(
            model_name='originreference',
            name='field_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='participanttype',
            name='status_validation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol'),
        ),
        migrations.AddField(
            model_name='sector',
            name='status_validation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol'),
        ),
        migrations.AddField(
            model_name='sectorgroup',
            name='capital_type',
            field=models.CharField(blank=True, choices=[('public', 'Público'), ('private', 'Privado'), ('mixed', 'Mixto'), ('conflict', 'Conflicto')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sectorgroup',
            name='has_belongs',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='CapitalType',
        ),
    ]
