# Generated by Django 4.2.9 on 2024-09-21 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0003_actor_others_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='network_seq',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='is_only_related',
            field=models.BooleanField(blank=True, null=True, verbose_name='Se creó solo por relación'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='parent_actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_actors', to='actor.actor', verbose_name='Actor padre'),
        ),
    ]
