# Generated by Django 4.2.9 on 2025-01-14 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0003_unaccent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='alternative_names',
            new_name='alt_names',
        ),
    ]
