# Generated by Django 4.2.9 on 2024-11-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0002_country'),
        ('actor', '0003_unaccent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='countries',
            field=models.ManyToManyField(blank=True, to='classify.country'),
        ),
    ]
