# Generated by Django 4.2.9 on 2025-06-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0003_alter_actor_others_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Texto de interés'),
        ),
    ]
