# Generated by Django 4.2.9 on 2025-01-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0004_rename_alternative_names_actor_alt_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='alternative_names',
            field=models.TextField(blank=True, null=True, verbose_name='Nombres alternativos'),
        ),
    ]
