# Generated by Django 4.2.9 on 2024-10-03 00:33

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0004_actor_network_seq_alter_actor_is_only_related_and_more'),
    ]

    operations = [
        CreateExtension('unaccent'),
    ]