# Generated by Django 4.2.9 on 2024-05-14 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0004_remove_actor_capital_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('director', 'Director'), ('investor', 'Inversionista'), ('chief_executive', 'Director Ejecutivo'), ('other', 'Otro directivo'), ('member', 'Integrante')], default='member', max_length=20)),
                ('actor_collective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_collective', to='actor.actor')),
                ('actor_individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_individual', to='actor.actor')),
            ],
            options={
                'verbose_name': 'Persona integrante de actor colectivo',
                'verbose_name_plural': 'Personas integrantes de actor colectivo',
            },
        ),
    ]
