# Generated by Django 4.2.9 on 2025-09-10 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0003_alter_interestgroup_options_and_more'),
        ('actor', '0004_alter_interest_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='interest_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='classify.participanttype'),
        ),
    ]
