# Generated by Django 5.2.6 on 2026-02-24 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0005_interest_interest_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='interest_type',
        ),
    ]
