# Generated by Django 4.2.9 on 2025-01-14 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0005_actor_alternative_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='official_name',
        ),
    ]
