# Generated by Django 4.2.9 on 2024-10-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0005_auto_20241002_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originreference',
            name='type_model',
            field=models.CharField(choices=[('Capital', 'Capital'), ('Estado', 'Estado'), ('Opositores', 'Opositores'), ('PoblacionesAfectadas', 'PoblacionesAfectadas'), ('GruposApoyo', 'GruposApoyo')], max_length=20),
        ),
    ]
