# Generated by Django 4.2.9 on 2025-01-14 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0006_remove_actor_official_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='alt_names',
        ),
    ]
