# Generated by Django 4.2.9 on 2024-10-29 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0006_alter_originreference_type_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='comments',
        ),
    ]
