# Generated by Django 4.2.9 on 2024-10-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0007_remove_actor_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
