# Generated by Django 4.2.9 on 2025-01-18 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0001_initial'),
        ('actor', '0007_remove_actor_alt_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='sector_name',
        ),
        migrations.AlterField(
            model_name='actor',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='classify.sector'),
        ),
    ]
