# Generated by Django 4.2.9 on 2025-01-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0003_alter_participantgroup_key_name_and_more'),
        ('actor', '0008_remove_actor_sector_name_alter_actor_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='participant_types',
            field=models.ManyToManyField(blank=True, related_name='participants', to='classify.participanttype'),
        ),
    ]
