# Generated by Django 4.2.9 on 2024-10-30 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0007_alter_interesttype_options_and_more'),
        ('actor', '0008_actor_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='indigenous_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='classify.indigenousgroup'),
        ),
    ]
