# Generated by Django 4.2.9 on 2025-01-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0008_alter_participanttype_participant_group'),
        ('actor', '0009_alter_participant_participant_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='belongs',
            field=models.ManyToManyField(blank=True, related_name='actors', to='classify.belong'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='actors', to='classify.country'),
        ),
    ]
