generic_responsable_estatal_desc = [
    "Ejército",
    "Agentes estatales",
    "Agentes judiciales",
    "Agentes municipales",
    "Ejercito",
    "Ejército",
    "Ejército Mexicano",
    "Elementos de la policía estatal ",
    "Estado mexicano ",
    "Fiscalía",
    "Fuerza pública",
    "Fuerzas Federales",
    "Fuerzas Públicas Estatales ",
    "Gendarmería ",
    "Policía municipal y estatal",
    "Gobierno  estatal",
    "Gorbierno Federal",
    "Granaderos",
    "NE",
    "Poder Judicial",
    "Polcía Militar",
    "Policia",
    "Policía",
    "Policía ",
    "Policía estatal",
    "Policía ministerial",
    "Policía Municipal",
    "Policias",
    "Policías",
    "Policías Estatales",
    "Polícías estatales",
    "Policías estatales ",
    "Policías estatales",
    "Policías federales",
    "Policías municipales",
    "Presidente municipal",
    "Presidente municipal ",
    "Protección Civil",
    "Secretaría de Gobierno",
    "Secretaría de Seguridad Ciudadana (SSC)",
    "Secretaría de Seguridad Pública",
    "Secretaría de Seguridad Pública (SSP)",
    "Secretaría de Seguridad Pública Estatal (SSPE)",
    "Tres niveles de gobierno",
    "Ejército Mexicano",
]
