generic_responsables = {
    "estatal": [
        "Ejército",
        "Agentes estatales",
        "Agentes judiciales",
        "Agentes municipales",
        "Ejercito",
        "Ejército",
        "Ejército Mexicano",
        "Elementos de la policía estatal ",
        "Estado mexicano ",
        "Fiscalía",
        "Fuerza pública",
        "Fuerzas Federales",
        "Fuerzas Públicas Estatales ",
        "Gendarmería ",
        "Policía municipal y estatal",
        "Gobierno  estatal",
        "Gorbierno Federal",
        "Granaderos",
        "NE",
        "Poder Judicial",
        "Polcía Militar",
        "Policia",
        "Policía",
        "Policía ",
        "Policía estatal",
        "Policía ministerial",
        "Policía Municipal",
        "Policias",
        "Policías",
        "Policías Estatales",
        "Polícías estatales",
        "Policías estatales ",
        "Policías estatales",
        "Policías federales",
        "Policías municipales",
        "Presidente municipal",
        "Presidente municipal ",
        "Protección Civil",
        "Secretaría de Gobierno",
        "Secretaría de Seguridad Ciudadana (SSC)",
        "Secretaría de Seguridad Pública",
        "Secretaría de Seguridad Pública (SSP)",
        "Secretaría de Seguridad Pública Estatal (SSPE)",
        "Tres niveles de gobierno",
        "Ejército Mexicano",
    ],
    "no_estatal": [
        "100 acarreados",
        "Civiles",
        "Civiles armados",
        "Comando armado",
        "Comisariado Ejidal",
        "Crimen orgaizado",
        "Crimen organizado",
        "Delincuencia organizada",
        "Delincuentes",
        "Empleados de la minera",
        "Empresa constructora",
        "Empresa encargada de la mina",
        "Empresario",
        "Empresarios de materiales",
        "Encapuchados",
        "Grupo armado",
        "Grupo armado ",
        "Grupo de choque",
        "Grupo de hombres armados",
        "Grupo de personas infiltradas",
        "Grupo delicuencial",
        "Grupo delincuencial ",
        "Grupos criminales",
        "Grupos criminales",
        "Grupos de choque",
        "Hombres armados",
        "Iniciativa privada",
        "Inversionistas",
        "Narcotráfico",
        "Notario público",
        "Paramilitares",
        "Personal armado",
        "Personal que trabajan para la inmobiliaria ",
        "Personas armadas",
        "Pistoleros",
        "Porros",
        "Presuntos agentes de la empresa",
        "Sicarios",
        "Sujetos armados",
        "Talamontes",
        "Talamontes ",
        "Talamontes y crimen organizado",
        "constructoras",
    ]
}