# Generated by Django 4.2.9 on 2024-05-16 00:17

from django.db import migrations, models
import django.db.models.deletion
import space_time.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flag_emoji', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inegi_code', models.CharField(max_length=6, verbose_name='Clave INEGI')),
                ('complete_code', models.CharField(max_length=10, verbose_name='Clave INEGI Completa')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('population', models.IntegerField(blank=True, null=True, verbose_name='Población')),
                ('is_rural', models.BooleanField(default=False, verbose_name='Es rural')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('altitude', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inegi_code', models.CharField(max_length=2, verbose_name='Clave INEGI')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('short_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre Corto')),
                ('code_name', models.CharField(blank=True, max_length=6, null=True, verbose_name='Nombre Clave')),
                ('alternative_names', models.JSONField(default=space_time.models.default_alternative_names, help_text='Ocupar para OCAMIS', verbose_name='Lista nombres alternativos')),
            ],
            options={
                'verbose_name': 'Entidad Federativa',
                'verbose_name_plural': 'Entidades Federativas',
                'ordering': ['inegi_code'],
            },
        ),
        migrations.CreateModel(
            name='StatusProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Status Project',
                'verbose_name_plural': 'Status Projects',
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inegi_code', models.CharField(max_length=6, verbose_name='Clave INEGI')),
                ('complete_code', models.CharField(max_length=8, verbose_name='Clave INEGI Completa')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('std_name', models.CharField(max_length=255, verbose_name='Nombre Estandarizado')),
                ('population', models.IntegerField(blank=True, null=True, verbose_name='Población')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='space_time.state', verbose_name='State')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['inegi_code'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('geojson', models.JSONField(blank=True, null=True)),
                ('ubicacion_id_ref', models.IntegerField(blank=True, null=True)),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='space_time.locality')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='space_time.municipality')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='space_time.state')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.AddField(
            model_name='locality',
            name='municipality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localities', to='space_time.municipality', verbose_name='Municipality'),
        ),
    ]
