# Generated by Django 4.2.9 on 2024-04-26 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatTemporalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Temporalidad',
                'verbose_name_plural': 'Temporalidades',
                'db_table': 'cat_temporalidad',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ubicacion', models.CharField(blank=True, default='punto', max_length=100, null=True)),
                ('estado', models.TextField(blank=True, null=True)),
                ('municipio', models.TextField(blank=True, null=True)),
                ('localidad', models.TextField(blank=True, null=True)),
                ('especificaciones', models.TextField(blank=True, null=True)),
                ('sitio', models.TextField(blank=True, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'db_table': 'ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Temporalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('intervalo', models.DurationField(blank=True, null=True)),
                ('day_undefined', models.BooleanField(blank=True, default=False, null=True)),
                ('month_undefined', models.BooleanField(blank=True, default=False, null=True)),
                ('cat_temporalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space_time.cattemporalidad')),
            ],
            options={
                'verbose_name': 'Temporalidad',
                'verbose_name_plural': 'Temporalidades',
                'db_table': 'temporalidad',
            },
        ),
    ]
