# Generated by Django 4.2.9 on 2024-11-20 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_flux', '0001_initial'),
        ('space_time', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='status_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol'),
        ),
    ]
