# Generated by Django 4.2.9 on 2024-04-30 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_time', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='country',
            table=None,
        ),
    ]
