# Generated by Django 5.2.17 on 2026-08-27 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_time', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='is_current',
            field=models.BooleanField(default=True, help_text='Las localidades que el INEGI retiró se marcan como no vigentes en vez de borrarse: hay ubicaciones antiguas que las usan.', verbose_name='Vigente en el catálogo INEGI'),
        ),
        migrations.AddField(
            model_name='location',
            name='municipalities',
            field=models.ManyToManyField(blank=True, help_text='Se calcula al guardar a partir del trazo; no se captura a mano.', related_name='crossed_locations', to='space_time.municipality', verbose_name='Municipios que abarca'),
        ),
        migrations.AddField(
            model_name='location',
            name='nearby_localities',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Cuántas localidades corta el trazo o quedan dentro de su margen de cercanía. Si es exactamente una, se llena el campo Localidad; con cero o más de una queda vacío.', null=True, verbose_name='Localidades que toca o roza'),
        ),
        migrations.CreateModel(
            name='LocalityGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wkb', models.BinaryField(verbose_name='Geometría (WKB, EPSG:6372)')),
                ('simplified_m', models.SmallIntegerField(default=50, verbose_name='Tolerancia de simplificación (m)')),
                ('locality', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geometry', to='space_time.locality', verbose_name='Localidad')),
            ],
            options={
                'verbose_name': 'Geometría de localidad',
                'verbose_name_plural': 'Geometrías de localidades',
            },
        ),
        migrations.CreateModel(
            name='MunicipalityGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wkb', models.BinaryField(verbose_name='Geometría (WKB, EPSG:6372)')),
                ('simplified_m', models.SmallIntegerField(default=50, verbose_name='Tolerancia de simplificación (m)')),
                ('municipality', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geometry', to='space_time.municipality', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Geometría de municipio',
                'verbose_name_plural': 'Geometrías de municipios',
            },
        ),
        migrations.CreateModel(
            name='StateGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wkb', models.BinaryField(verbose_name='Geometría (WKB, EPSG:6372)')),
                ('simplified_m', models.SmallIntegerField(default=50, verbose_name='Tolerancia de simplificación (m)')),
                ('state', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geometry', to='space_time.state', verbose_name='Entidad Federativa')),
            ],
            options={
                'verbose_name': 'Geometría de entidad',
                'verbose_name_plural': 'Geometrías de entidades',
            },
        ),
    ]
