# Generated by Django 4.2.9 on 2024-11-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_time', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
