# Generated by Django 5.2.17 on 2026-08-28 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_time', '0002_geometrias_y_municipios_atravesados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='nearby_localities',
        ),
    ]
