# Generated by Django 4.2.9 on 2025-01-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_time', '0002_location_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='type_location',
            field=models.CharField(choices=[('point', 'Punto'), ('polygon', 'Polígono'), ('line', 'Línea')], default='point', max_length=10),
        ),
    ]
