# Generated by Django 4.2.9 on 2024-10-11 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_time', '0002_alter_country_options_statusproject_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusproject',
            options={'ordering': ['order'], 'verbose_name': 'Status Project', 'verbose_name_plural': 'Status Projects'},
        ),
    ]
