# Generated by Django 4.2.9 on 2024-05-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_time', '0002_locality_state_municipality_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='geojson',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
