# Generated by Django 4.2.9 on 2024-11-26 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_time', '0002_location_status_location'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='country',
            table='space_time_country',
        ),
    ]
