# Generated by Django 4.2.9 on 2024-11-26 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0004_alter_actor_countries'),
        ('space_time', '0003_alter_country_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
