# Generated by Django 4.2.9 on 2025-01-21 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0005_impactgroup_description'),
        ('space_time', '0003_location_type_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='impact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='impact.impact'),
        ),
    ]
