# Generated by Django 4.2.9 on 2024-10-20 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_time', '0003_alter_statusproject_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'Pais', 'verbose_name_plural': 'Paises'},
        ),
    ]
