# Generated by Django 4.2.9 on 2024-11-26 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_time', '0004_delete_country'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='statusproject',
            table='space_time_statusproject',
        ),
    ]
