# Generated by Django 4.2.9 on 2024-10-29 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_flux', '0002_statuscontrol_is_public'),
        ('space_time', '0004_alter_country_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusproject',
            name='status_validation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol'),
        ),
    ]
