# Generated by Django 4.2.9 on 2024-11-26 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_statusproject_alter_project_status_project'),
        ('source', '0003_alter_statushistory_status_project'),
        ('space_time', '0005_alter_statusproject_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusProject',
        ),
    ]
