# Generated by Django 4.2.9 on 2024-10-30 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_time', '0005_statusproject_status_validation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusproject',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Status Project', 'verbose_name_plural': 'Status Projects'},
        ),
    ]
