# Generated by Django 4.2.9 on 2024-10-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_time', '0006_alter_statusproject_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusproject',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
