# Generated by Django 4.2.9 on 2024-06-25 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work_flux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Belong',
            fields=[
                ('key_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Grupo de Pertenencia (Vulnerabilidad)',
                'verbose_name_plural': 'Grupos de Pertenencia (Vulnerabilidades)',
            },
        ),
        migrations.CreateModel(
            name='IndigenousGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Grupo Indígena',
                'verbose_name_plural': 'Grupos Indígenas',
            },
        ),
        migrations.CreateModel(
            name='InterestGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.CharField(choices=[('denuncia', 'Denuncia'), ('demanda', 'Demanda'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Agrupador de tipos de interés',
                'verbose_name_plural': 'Agrupadores de tipos de interés',
            },
        ),
        migrations.CreateModel(
            name='ParticipantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[('undefined', 'No definido'), ('maybe_support', 'Posiblemente a favor'), ('support', 'A favor'), ('oppose', 'En contra'), ('neutral', 'Neutral'), ('other', 'Otro')], default='undefined', max_length=14)),
                ('required_interests', models.BooleanField(default=True, verbose_name='Se requerirá que se agreguen intereses')),
                ('description', models.TextField(blank=True, null=True)),
                ('status_validation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol')),
            ],
            options={
                'verbose_name': 'Tipo de Participación en Proyecto',
                'verbose_name_plural': 'Tipos de Participación en Proyecto',
            },
        ),
        migrations.CreateModel(
            name='SectorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_collective', models.BooleanField(blank=True, null=True)),
                ('has_belongs', models.BooleanField(default=True)),
                ('capital_type', models.CharField(blank=True, choices=[('public', 'Público'), ('private', 'Privado'), ('mixed', 'Mixto'), ('conflict', 'Conflicto')], max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Grupo Sectorial',
                'verbose_name_plural': 'Grupos Sectoriales',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('needs_name', models.BooleanField(default=False)),
                ('common_belongs', models.ManyToManyField(blank=True, to='classify.belong')),
                ('common_participant_types', models.ManyToManyField(blank=True, to='classify.participanttype')),
                ('sector_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classify.sectorgroup')),
                ('status_validation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
            },
        ),
        migrations.CreateModel(
            name='InterestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classify.interestgroup')),
            ],
            options={
                'verbose_name': 'Tipo de Interés',
                'verbose_name_plural': 'Tipos de Interés',
            },
        ),
        migrations.AddField(
            model_name='interestgroup',
            name='participant_types',
            field=models.ManyToManyField(blank=True, to='classify.participanttype'),
        ),
    ]
