# Generated by Django 4.2.9 on 2024-11-06 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work_flux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Belong',
            fields=[
                ('key_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.SmallIntegerField(default=5)),
            ],
            options={
                'verbose_name': 'Grupo de Pertenencia (Vulnerabilidad)',
                'verbose_name_plural': 'Grupos de Pertenencia (Vulnerabilidades)',
                'ordering': ['order', 'key_name'],
            },
        ),
        migrations.CreateModel(
            name='InterestGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.SmallIntegerField(default=5)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Agrupador de tipos de interés',
                'verbose_name_plural': 'Agrupadores de tipos de interés',
            },
        ),
        migrations.CreateModel(
            name='ParticipantGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('key_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.SmallIntegerField(default=5)),
            ],
            options={
                'verbose_name': 'Tipo de Participante',
                'verbose_name_plural': 'Tipos de Participantes',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[('support', 'A favor'), ('oppose', 'En contra'), ('neutral', 'Neutral'), ('other', 'Otro')], default='undefined', max_length=14)),
                ('required_interests', models.BooleanField(default=True, verbose_name='Se requerirá que se agreguen intereses')),
                ('comments', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.SmallIntegerField(default=5)),
                ('participant_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classify.participantgroup')),
                ('status_validation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol')),
            ],
            options={
                'verbose_name': 'Subtipo de Participación en Proyecto',
                'verbose_name_plural': 'Subtipo de Participación en Proyecto',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SectorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_collective', models.BooleanField(blank=True, null=True)),
                ('has_belongs', models.BooleanField(default=True)),
                ('capital_type', models.CharField(blank=True, choices=[('public', 'Público'), ('private', 'Privado'), ('mixed', 'Mixto'), ('conflict', 'Conflicto')], max_length=10, null=True)),
                ('icon', models.CharField(blank=True, max_length=90, null=True)),
                ('order', models.SmallIntegerField(default=10)),
                ('comments', models.TextField(blank=True, null=True)),
                ('status_validation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol')),
            ],
            options={
                'verbose_name': 'Grupo Sectorial',
                'verbose_name_plural': 'Grupos Sectoriales',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('needs_name', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('order', models.SmallIntegerField(default=50)),
                ('common_belongs', models.ManyToManyField(blank=True, to='classify.belong')),
                ('common_participant_types', models.ManyToManyField(blank=True, to='classify.participanttype')),
                ('sector_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classify.sectorgroup')),
                ('status_validation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InterestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('order', models.SmallIntegerField(default=5)),
                ('interest_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classify.interestgroup')),
                ('participant_types', models.ManyToManyField(blank=True, to='classify.participanttype')),
                ('status_validation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol')),
            ],
            options={
                'verbose_name': 'Tipo de interés',
                'verbose_name_plural': 'Tipos de interés',
            },
        ),
        migrations.CreateModel(
            name='InterestSubtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('order', models.SmallIntegerField(default=20)),
                ('interest_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classify.interesttype')),
                ('status_validation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol')),
            ],
            options={
                'verbose_name': 'Subtipo de interés',
                'verbose_name_plural': 'Subtipos de interés',
            },
        ),
        migrations.CreateModel(
            name='IndigenousGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('status_validation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol')),
            ],
            options={
                'verbose_name': 'Grupo Indígena',
                'verbose_name_plural': 'Grupos Indígenas',
                'ordering': ['name'],
            },
        ),
    ]
