# Generated by Django 4.2.9 on 2024-09-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='belong',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
