# Generated by Django 4.2.9 on 2025-01-19 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='needs_name',
        ),
        migrations.AlterField(
            model_name='sector',
            name='sector_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='classify.sectorgroup'),
        ),
    ]
