# Generated by Django 4.2.9 on 2025-01-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interesttype',
            name='participant_types',
            field=models.ManyToManyField(blank=True, related_name='interest_types', to='classify.participanttype'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='common_belongs',
            field=models.ManyToManyField(blank=True, related_name='sectors', to='classify.belong'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='common_participant_types',
            field=models.ManyToManyField(blank=True, related_name='sectors', to='classify.participanttype'),
        ),
    ]
