# Generated by Django 4.2.9 on 2025-01-20 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0002_remove_sector_needs_name_alter_sector_sector_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantgroup',
            name='key_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='participanttype',
            name='participant_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_types', to='classify.participantgroup'),
        ),
        migrations.AlterField(
            model_name='participanttype',
            name='position',
            field=models.CharField(choices=[('support', 'A favor'), ('oppose', 'En contra'), ('neutral', 'Neutral'), ('other', 'Otro'), ('undefined', 'Indefinido')], default='undefined', max_length=14),
        ),
    ]
