# Generated by Django 4.2.9 on 2025-01-30 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0002_alter_interesttype_participant_types_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interestgroup',
            options={'ordering': ['order'], 'verbose_name': 'Agrupador de tipos de interés', 'verbose_name_plural': 'Agrupadores de tipos de interés'},
        ),
        migrations.AlterModelOptions(
            name='interestsubtype',
            options={'ordering': ['order'], 'verbose_name': 'Subtipo de interés', 'verbose_name_plural': 'Subtipos de interés'},
        ),
        migrations.AlterModelOptions(
            name='interesttype',
            options={'ordering': ['order'], 'verbose_name': 'Tipo de interés', 'verbose_name_plural': 'Tipos de interés'},
        ),
    ]
