# Generated by Django 4.2.9 on 2024-11-26 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0002_country'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='country',
            table='classify_country',
        ),
    ]
