# Generated by Django 4.2.9 on 2024-09-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0002_belong_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectorgroup',
            name='icon',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
