# Generated by Django 4.2.9 on 2025-09-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0003_alter_interestgroup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectorgroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
