# Generated by Django 4.2.9 on 2024-10-01 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_flux', '0001_initial'),
        ('classify', '0003_sectorgroup_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indigenousgroup',
            options={'ordering': ['name'], 'verbose_name': 'Grupo Indígena', 'verbose_name_plural': 'Grupos Indígenas'},
        ),
        migrations.AddField(
            model_name='belong',
            name='order',
            field=models.SmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='interestgroup',
            name='order',
            field=models.SmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='interestgroup',
            name='status_validation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol'),
        ),
        migrations.AddField(
            model_name='interesttype',
            name='order',
            field=models.SmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='interesttype',
            name='status_validation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol'),
        ),
        migrations.AddField(
            model_name='participanttype',
            name='order',
            field=models.SmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='sector',
            name='order',
            field=models.SmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='sectorgroup',
            name='order',
            field=models.SmallIntegerField(default=10),
        ),
    ]
