# Generated by Django 4.2.9 on 2025-01-20 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0003_alter_participantgroup_key_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participantgroup',
            old_name='key_name',
            new_name='short_name',
        ),
    ]
