# Generated by Django 4.2.9 on 2025-01-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0003_alter_participantgroup_key_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participanttype',
            name='participant_group',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
