# Generated by Django 4.2.9 on 2025-01-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0004_alter_participanttype_participant_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantgroup',
            name='id',
        ),
        migrations.AlterField(
            model_name='participantgroup',
            name='key_name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
