# Generated by Django 4.2.9 on 2024-10-11 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0004_alter_indigenousgroup_options_belong_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='belong',
            options={'ordering': ['order', 'key_name'], 'verbose_name': 'Grupo de Pertenencia (Vulnerabilidad)', 'verbose_name_plural': 'Grupos de Pertenencia (Vulnerabilidades)'},
        ),
        migrations.AlterModelOptions(
            name='participanttype',
            options={'ordering': ['order'], 'verbose_name': 'Tipo de Participación en Proyecto', 'verbose_name_plural': 'Tipos de Participación en Proyecto'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Sector', 'verbose_name_plural': 'Sectores'},
        ),
        migrations.AlterModelOptions(
            name='sectorgroup',
            options={'ordering': ['order'], 'verbose_name': 'Grupo Sectorial', 'verbose_name_plural': 'Grupos Sectoriales'},
        ),
    ]
