# Generated by Django 5.2.6 on 2025-10-30 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0004_sector_description_sectorgroup_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='common_belongs',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='common_participant_types',
        ),
    ]
