# Generated by Django 4.2.9 on 2024-10-14 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0005_alter_belong_options_alter_participanttype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('key_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.SmallIntegerField(default=5)),
            ],
            options={
                'verbose_name': 'Grupo de Participantes',
                'verbose_name_plural': 'Grupos de Participantes',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='participanttype',
            name='position',
            field=models.CharField(choices=[('support', 'A favor'), ('oppose', 'En contra'), ('neutral', 'Neutral'), ('other', 'Otro')], default='undefined', max_length=14),
        ),
        migrations.AddField(
            model_name='participanttype',
            name='participant_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classify.participantgroup'),
        ),
    ]
