# Generated by Django 4.2.9 on 2025-01-20 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0005_remove_participantgroup_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participanttype',
            name='participant_group',
        ),
    ]
