# Generated by Django 5.2.6 on 2025-10-30 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0005_remove_sector_common_belongs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interesttype',
            name='participant_types',
        ),
    ]
