# Generated by Django 4.2.9 on 2025-01-20 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0006_remove_participanttype_participant_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participanttype',
            old_name='position',
            new_name='participant_group',
        ),
    ]
