# Generated by Django 5.2.6 on 2026-05-19 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0006_remove_interesttype_participant_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indigenousgroup',
            options={'ordering': ['name'], 'verbose_name': 'Pueblo Indígena', 'verbose_name_plural': 'Pueblos Indígenas'},
        ),
    ]
