# Generated by Django 4.2.9 on 2024-10-20 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_flux', '0002_statuscontrol_is_public'),
        ('classify', '0006_participantgroup_alter_participanttype_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interesttype',
            options={'verbose_name': 'Tipo de interés', 'verbose_name_plural': 'Tipos de interés'},
        ),
        migrations.RenameField(
            model_name='interesttype',
            old_name='group',
            new_name='interest_group',
        ),
        migrations.RemoveField(
            model_name='interestgroup',
            name='cluster',
        ),
        migrations.RemoveField(
            model_name='interestgroup',
            name='participant_types',
        ),
        migrations.RemoveField(
            model_name='interestgroup',
            name='status_validation',
        ),
        migrations.AddField(
            model_name='indigenousgroup',
            name='status_validation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol'),
        ),
        migrations.AddField(
            model_name='interestgroup',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interestgroup',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interesttype',
            name='participant_types',
            field=models.ManyToManyField(blank=True, to='classify.participanttype'),
        ),
        migrations.AlterField(
            model_name='interesttype',
            name='order',
            field=models.SmallIntegerField(default=5),
        ),
        migrations.CreateModel(
            name='InterestSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.SmallIntegerField(default=20)),
                ('interest_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classify.interesttype')),
                ('status_validation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol')),
            ],
            options={
                'verbose_name': 'Subtipo de interés',
                'verbose_name_plural': 'Subtipos de interés',
            },
        ),
    ]
