# Generated by Django 4.2.9 on 2025-01-20 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0007_rename_position_participanttype_participant_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participanttype',
            name='participant_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_types', to='classify.participantgroup'),
        ),
    ]
