# Generated by Django 4.2.9 on 2024-10-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0007_alter_interesttype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indigenousgroup',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interestsubtype',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interesttype',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participanttype',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
