# Generated by Django 4.2.9 on 2024-10-30 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_flux', '0002_statuscontrol_is_public'),
        ('classify', '0008_indigenousgroup_comments_interestsubtype_comments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participantgroup',
            options={'ordering': ['order'], 'verbose_name': 'Tipo de Participante', 'verbose_name_plural': 'Tipos de Participantes'},
        ),
        migrations.AlterModelOptions(
            name='participanttype',
            options={'ordering': ['order'], 'verbose_name': 'Subtipo de Participación en Proyecto', 'verbose_name_plural': 'Subtipo de Participación en Proyecto'},
        ),
        migrations.AddField(
            model_name='sectorgroup',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectorgroup',
            name='status_validation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol'),
        ),
    ]
