# Generated by Django 4.2.9 on 2024-04-25 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
        ('ubication', '0001_initial'),
        ('tempo_extend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'CSA',
                'verbose_name_plural': 'CSAs',
                'db_table': 'csa',
            },
        ),
        migrations.CreateModel(
            name='EstatusProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Estatus Proyecto',
                'verbose_name_plural': 'Estatus Proyectos',
                'db_table': 'cat_estatus_proyecto',
            },
        ),
        migrations.CreateModel(
            name='TipoDespliegueCapital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo Despliegue Capital',
                'verbose_name_plural': 'Tipos Despliegue Capital',
                'db_table': 'cat_tipo_despliegue_capital',
            },
        ),
        migrations.CreateModel(
            name='TipoMegaproyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Tipo Megaproyecto',
                'verbose_name_plural': 'Tipos Megaproyecto',
                'db_table': 'cat_tipo_megaproyecto',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mp', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('escala', models.CharField(max_length=100)),
                ('especificaciones', models.TextField()),
                ('old_ubis', models.BigIntegerField()),
                ('csa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.csa')),
                ('proyecto_vinculado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.proyecto')),
                ('tipo_despliegue_capital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.tipodesplieguecapital')),
                ('tipo_megaproyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.tipomegaproyecto')),
                ('ubicaciones', models.ManyToManyField(db_table='ocs.proyectos_to_ubicaciones', to='ubication.ubicacion')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'proyectos',
            },
        ),
        migrations.CreateModel(
            name='EstatusProyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.estatusproyecto')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.nota')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.proyecto')),
                ('temporalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tempo_extend.temporalidad')),
            ],
            options={
                'verbose_name': 'Estatus Proyecto',
                'verbose_name_plural': 'Estatus Proyectos',
                'db_table': 'estatus_proyectos',
            },
        ),
    ]
