# Generated by Django 4.2.9 on 2025-07-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_editor',
            field=models.BooleanField(default=False, help_text='Puede agregar notas, comentarios a los registros,pero no tiene todos los permisos', verbose_name='Es capturista'),
        ),
    ]
