# Generated by Django 4.2.9 on 2024-11-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_editor',
            field=models.BooleanField(default=False, help_text='Puede editar cualquier contenido', verbose_name='Es revisor'),
        ),
    ]
