# Generated by Django 5.2.6 on 2025-09-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_auth', '0002_alter_user_full_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mini_editor',
            field=models.BooleanField(default=False, help_text='Puede modificar ubicaciones y otros detalles', verbose_name='Servicio social'),
        ),
    ]
