# Generated by Django 4.2.9 on 2024-04-25 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_propiedad', models.CharField(max_length=100)),
                ('fortalecimiento_tejido_social', models.TextField()),
                ('descripcion', models.TextField()),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.nota')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.proyecto')),
            ],
            options={
                'verbose_name': 'Otro',
                'verbose_name_plural': 'Otros',
                'db_table': 'otros',
            },
        ),
    ]
