# Generated by Django 4.2.9 on 2024-10-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_schema', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['order'], 'verbose_name': 'Modelo (Colección)', 'verbose_name_plural': '1.1 Modelos (Colecciones)'},
        ),
        migrations.AddField(
            model_name='collectionlink',
            name='is_mandatory',
            field=models.BooleanField(default=False),
        ),
    ]
