# Generated by Django 4.2.9 on 2025-01-28 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ps_schema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='status_groups',
        ),
    ]
