# Generated by Django 4.2.9 on 2024-12-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_schema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='available_actions',
            field=models.JSONField(default=list, verbose_name='Acciones disponibles'),
        ),
    ]
