# Generated by Django 4.2.9 on 2025-06-16 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_schema', '0002_remove_collection_status_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='xls_export',
            field=models.BooleanField(default=False, verbose_name='Tiene exportación a excel'),
        ),
    ]
