# Generated by Django 4.2.9 on 2024-10-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_schema', '0002_alter_collection_options_collectionlink_is_mandatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtergroup',
            name='addl_config',
            field=models.JSONField(default=dict, verbose_name='Configuración adicional'),
        ),
    ]
