# Generated by Django 4.2.9 on 2025-01-25 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ps_schema', '0002_collection_available_actions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='status_groups',
        ),
    ]
