# Generated by Django 4.2.9 on 2024-10-22 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_schema', '0003_filtergroup_addl_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filtergroup',
            name='filter_collections',
        ),
        migrations.AddField(
            model_name='collection',
            name='all_filters',
            field=models.JSONField(default=list, verbose_name='Grupos de filtros'),
        ),
    ]
