# Generated by Django 4.2.9 on 2025-07-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_schema', '0003_collection_xls_export'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='cat_params',
            field=models.JSONField(blank=True, default=dict, verbose_name='Parámetros para el catálogo'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='sort_fields',
            field=models.JSONField(blank=True, default=list, verbose_name='Campos de ordenamiento'),
        ),
    ]
