# Generated by Django 4.2.9 on 2024-10-23 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ps_schema', '0004_remove_filtergroup_filter_collections_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='order',
            field=models.SmallIntegerField(default=5, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='collectionlink',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='ps_schema.collection'),
        ),
        migrations.AlterField(
            model_name='collectionlink',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_links', to='ps_schema.collection'),
        ),
    ]
