# Generated by Django 5.2.6 on 2026-02-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_schema', '0004_alter_collection_cat_params_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='available_actions',
            field=models.JSONField(blank=True, default=list, verbose_name='Acciones disponibles'),
        ),
    ]
