# Generated by Django 5.2.6 on 2026-02-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_schema', '0005_alter_collection_available_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='all_filters',
            field=models.JSONField(blank=True, default=list, verbose_name='Grupos de filtros'),
        ),
    ]
