# Generated by Django 4.2.9 on 2024-10-23 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ps_schema', '0005_alter_collection_order_alter_collectionlink_child_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionlink',
            name='filter_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='ps_schema.filtergroup'),
        ),
    ]
