# Generated by Django 5.2.6 on 2026-04-02 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ps_schema', '0006_alter_collection_all_filters'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollectionLink',
        ),
    ]
