# Generated by Django 4.2.9 on 2024-10-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_schema', '0006_collectionlink_filter_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='status_group',
        ),
        migrations.AddField(
            model_name='collection',
            name='status_groups',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
