# Generated by Django 4.2.9 on 2024-11-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_schema', '0007_remove_collection_status_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='fields',
            field=models.JSONField(default=list, verbose_name='Campos'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='icon',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Ícono'),
        ),
    ]
