# Generated by Django 5.2.6 on 2026-04-02 21:00

from django.db import migrations, models


def delete_catalog_collections(apps, schema_editor):
    Collection = apps.get_model('ps_schema', 'Collection')
    Collection.objects.filter(level__startswith='category_').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ps_schema', '0007_delete_collectionlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='level',
            field=models.CharField(choices=[('primary', 'Colección principal'), ('secondary', 'Colección secundaria'), ('relational', 'Colección relacional'), ('category_group', 'Grupo de categorías'), ('category_type', 'Tipo de categoría'), ('category_subtype', 'Subtipo de categoría')], max_length=40, verbose_name='Nivel'),
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['order'], 'verbose_name': 'Colección', 'verbose_name_plural': '1.1 Colecciones'},
        ),
        migrations.RemoveField(
            model_name='collection',
            name='all_filters',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='app_label',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='available_actions',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='cat_params',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='fields',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='name',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='open_insertion',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='optional_category',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='plural_name',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='sort_fields',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='xls_export',
        ),
        migrations.DeleteModel(
            name='FilterGroup',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.RunPython(
            delete_catalog_collections,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
