# Generated by Django 4.2.9 on 2025-01-29 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0005_purpose_event_purpose'),
        ('impact', '0004_remove_impactgroup_show_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Displacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massive_type', models.CharField(max_length=255)),
                ('rithm', models.CharField(max_length=255)),
                ('dimension', models.CharField(max_length=255)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='displacements', to='event.event')),
                ('impact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='displacements', to='impact.impact')),
            ],
            options={
                'verbose_name': 'Desplazamiento forzado',
                'verbose_name_plural': 'Desplazamientos forzados',
            },
        ),
    ]
