# Generated by Django 4.2.9 on 2025-01-30 15:20

from django.db import migrations, models
import django.db.models.deletion


def initial_dimensions(apps, schema_editor):
    # from df.models import Dimension
    Dimension = apps.get_model('df', 'Dimension')
    Dimension.objects.bulk_create([
        Dimension(
            name='Interno', order=1, show_countries=False, show_states=True),
        Dimension(
            name='Internacional', order=2, show_countries=True,
            show_states=False),
    ])


def initial_population_sizes(apps, schema_editor):
    # from df.models import PopulationSize
    PopulationSize = apps.get_model('df', 'PopulationSize')
    PopulationSize.objects.bulk_create([
        PopulationSize(name='Individuos y/o familias', order=1),
        PopulationSize(name='Masivo - Comunidades enteras', order=2),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('df', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.SmallIntegerField(default=5)),
                ('show_countries', models.BooleanField(default=False)),
                ('show_states', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Dimensión',
                'verbose_name_plural': 'Dimensiones',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PopulationSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.SmallIntegerField(default=5)),
            ],
            options={
                'verbose_name': 'Población afectada por desplazamiento',
                'verbose_name_plural': 'Poblaciones afectadas por desplazamiento',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='displacement',
            name='massive_type',
        ),
        migrations.AddField(
            model_name='displacement',
            name='population_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='df.populationsize'),
        ),
        migrations.AlterField(
            model_name='displacement',
            name='dimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='df.dimension'),
        ),
        migrations.RunPython(initial_dimensions),
        migrations.RunPython(initial_population_sizes),
    ]
