# Generated by Django 4.2.9 on 2025-02-16 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df', '0003_populationsize_comments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dimension',
            options={'ordering': ['order'], 'verbose_name': 'Dimensión del desplazamiento', 'verbose_name_plural': 'Dimensiones de desplazamientos'},
        ),
    ]
