# Generated by Django 4.2.9 on 2025-04-04 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space_time', '0001_initial'),
        ('classify', '0003_alter_interestgroup_options_and_more'),
        ('df', '0004_alter_dimension_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temporality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.SmallIntegerField(default=5)),
            ],
            options={
                'verbose_name': 'Temporalidad del desplazamiento',
                'verbose_name_plural': 'Temporalidades de desplazamientos',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='displacement',
            name='destination_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='displacement_destination', to='classify.country'),
        ),
        migrations.AddField(
            model_name='displacement',
            name='destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='displacement_destination', to='space_time.location'),
        ),
        migrations.AddField(
            model_name='displacement',
            name='destination_municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='displacement_destination', to='space_time.municipality'),
        ),
        migrations.AddField(
            model_name='displacement',
            name='destination_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='displacement_destination', to='space_time.state'),
        ),
        migrations.AddField(
            model_name='displacement',
            name='origin_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='displacement_origin', to='space_time.location'),
        ),
        migrations.AddField(
            model_name='displacement',
            name='origin_municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='displacement_origin', to='space_time.municipality'),
        ),
        migrations.AddField(
            model_name='displacement',
            name='origin_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='displacement_origin', to='space_time.state'),
        ),
        migrations.AddField(
            model_name='displacement',
            name='temporality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='df.temporality'),
        ),
    ]
