# Generated by Django 4.2.9 on 2025-06-24 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space_time', '0001_initial'),
        ('df', '0005_temporality_displacement_destination_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='displacement',
            name='destination_location',
        ),
        migrations.RemoveField(
            model_name='displacement',
            name='origin_location',
        ),
        migrations.AddField(
            model_name='displacement',
            name='destination_locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='displacement_destination', to='space_time.locality'),
        ),
        migrations.AddField(
            model_name='displacement',
            name='origin_locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='displacement_origin', to='space_time.locality'),
        ),
    ]
