# Generated by Django 4.2.9 on 2025-09-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df', '0006_remove_displacement_destination_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displacement',
            name='rithm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
