# Generated by Django 5.2.6 on 2026-03-30 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df', '0007_alter_displacement_rithm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displacement',
            name='dimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='displacements', to='df.dimension'),
        ),
        migrations.AlterField(
            model_name='displacement',
            name='population_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='displacements', to='df.populationsize'),
        ),
        migrations.AlterField(
            model_name='displacement',
            name='temporality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='displacements', to='df.temporality'),
        ),
    ]
