# Generated by Django 5.2.6 on 2025-11-25 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project_editors'),
        ('source', '0024_scrapedrecord_date_ended_scrapedrecord_user'),
        ('space_time', '0001_initial'),
        ('task', '0002_alter_clickhistory_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickhistory',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='source.article', verbose_name='Artículo'),
        ),
        migrations.AlterField(
            model_name='clickhistory',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='space_time.location', verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='clickhistory',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='source.note', verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='clickhistory',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='project.project', verbose_name='Proyecto'),
        ),
    ]
