# Generated by Django 5.2.6 on 2025-11-28 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_clickhistory_article_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clickhistory',
            options={'ordering': ['-date_start'], 'verbose_name': 'Historial', 'verbose_name_plural': 'Historial'},
        ),
        migrations.RenameField(
            model_name='clickhistory',
            old_name='date',
            new_name='date_start',
        ),
        migrations.CreateModel(
            name='OfflineTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(verbose_name='Inicio')),
                ('date_end', models.DateTimeField(verbose_name='Fin')),
                ('activity_type', models.CharField(choices=[('weekly_meeting', 'Reunión semanal'), ('meeting', 'Reunión'), ('training', 'Capacitación'), ('other', 'Otro')], max_length=100, verbose_name='Tipo')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Actividad')),
                ('user_added', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='offline_tasks_added', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='offline_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea offline',
                'verbose_name_plural': 'Tareas offline',
                'ordering': ['-date_start'],
            },
        ),
    ]
