# Generated by Django 4.2.9 on 2024-11-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_flux', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuscontrol',
            name='group',
            field=models.CharField(choices=[('register', 'Registro'), ('validation', 'Validación'), ('location', 'Ubicación')], default='petition', max_length=10, verbose_name='grupo de status'),
        ),
    ]
