# Generated by Django 4.2.9 on 2025-01-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_flux', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuscontrol',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
