# Generated by Django 4.2.9 on 2025-07-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_flux', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuscontrol',
            name='open_editor',
            field=models.BooleanField(default=True, verbose_name='Abierto a todxs'),
        ),
    ]
