# Generated by Django 4.2.9 on 2024-10-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_flux', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuscontrol',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
