# Generated by Django 4.2.9 on 2025-09-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_flux', '0002_alter_statuscontrol_open_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuscontrol',
            name='icon',
            field=models.CharField(blank=True, help_text='https://fonts.google.com/icons', max_length=40, null=True),
        ),
    ]
