# Generated by Django 5.2.6 on 2025-11-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_flux', '0003_alter_statuscontrol_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuscontrol',
            name='group',
            field=models.CharField(choices=[('register', 'Registro'), ('validation', 'Validación'), ('location', 'Ubicación'), ('retro', 'Retroalimentación')], default='petition', max_length=10, verbose_name='grupo de status'),
        ),
    ]
