# Generated by Django 5.2.6 on 2026-02-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_flux', '0004_alter_statuscontrol_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuscontrol',
            name='open_selectable',
            field=models.BooleanField(default=True, help_text='Se puede seleccionar la categoría', verbose_name='open selectable'),
        ),
        migrations.AlterField(
            model_name='statuscontrol',
            name='open_editor',
            field=models.BooleanField(default=True, help_text='Se puede cambiar a este status', verbose_name='open editor'),
        ),
    ]
