# Generated by Django 5.2.17 on 2026-08-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_flux', '0005_statuscontrol_open_selectable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuscontrol',
            name='open_editor',
            field=models.BooleanField(default=True, help_text='Los registros que están en este status pueden editarse —y cambiarse de status— por cualquier editor; apagado, solo los editores plenos y el staff.', verbose_name='edición abierta'),
        ),
        migrations.AlterField(
            model_name='statuscontrol',
            name='open_selectable',
            field=models.BooleanField(default=True, help_text='Este status puede elegirse como nuevo status al capturar; apagado, solo los editores plenos y el staff pueden asignarlo (p. ej. status heredados de la v.1 o de uso interno).', verbose_name='seleccionable como destino'),
        ),
    ]
