# Generated by Django 5.2.17 on 2026-08-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_flux', '0006_status_flags_help_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statuscontrol',
            old_name='is_deleted',
            new_name='is_legacy',
        ),
        migrations.AlterField(
            model_name='statuscontrol',
            name='is_legacy',
            field=models.BooleanField(default=False, help_text='Ya no participa del flujo vivo: no se asigna ni se ofrece; se conserva porque hay registros históricos que lo usan.', verbose_name='status legacy'),
        ),
    ]
