# Generated by Django 4.2.9 on 2024-06-25 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actor', '0001_initial'),
        ('work_flux', '0001_initial'),
        ('source', '0001_initial'),
        ('space_time', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model_origin', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('help_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rol en Evento',
                'verbose_name_plural': 'Roles en Eventos',
            },
        ),
        migrations.CreateModel(
            name='Involved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_women', models.IntegerField(blank=True, null=True)),
                ('number_men', models.IntegerField(blank=True, null=True)),
                ('number_mix', models.IntegerField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('event_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.eventrole')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actor.participant')),
            ],
            options={
                'verbose_name': 'Involucrado en Evento',
                'verbose_name_plural': 'Involucrados en Eventos',
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.eventgroup')),
                ('status_validation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol')),
            ],
            options={
                'verbose_name': 'Tipo de Evento',
                'verbose_name_plural': 'Tipos de Eventos',
            },
        ),
        migrations.CreateModel(
            name='EventSubtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('event_types', models.ManyToManyField(blank=True, to='event.eventtype')),
                ('status_validation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol')),
            ],
            options={
                'verbose_name': 'Subtipo de Evento',
                'verbose_name_plural': 'Subtipos de Eventos',
            },
        ),
        migrations.CreateModel(
            name='EventLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space_time.location')),
                ('status_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol')),
            ],
            options={
                'verbose_name': 'Ubicación de Evento',
                'verbose_name_plural': 'Ubicaciones de Eventos',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='event_subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.eventsubtype'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.eventtype'),
        ),
        migrations.AddField(
            model_name='event',
            name='mention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='source.mention'),
        ),
    ]
