# Generated by Django 4.2.9 on 2024-04-26 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actor', '0001_initial'),
        ('source', '__first__'),
        ('project', '__first__'),
        ('space_time', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccionesColectivas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Acción Colectiva',
                'verbose_name_plural': 'Acciones Colectivas',
                'db_table': 'acciones_colectivas',
            },
        ),
        migrations.CreateModel(
            name='CondicionMujerVictima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Condición Mujer Víctima',
                'verbose_name_plural': 'Condiciones Mujer Víctima',
                'db_table': 'cat_condicion_mujer_victima',
            },
        ),
        migrations.CreateModel(
            name='FormaAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Forma Acción Colectiva',
                'verbose_name_plural': 'Formas Acciones Colectivas',
                'db_table': 'cat_forma_ac',
            },
        ),
        migrations.CreateModel(
            name='FormaHechoViolencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Forma Hecho Violencia',
                'verbose_name_plural': 'Formas Hecho Violencia',
                'db_table': 'cat_forma_hecho_violencia',
            },
        ),
        migrations.CreateModel(
            name='HechosViolencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hecho Violencia',
                'verbose_name_plural': 'Hechos Violencia',
                'db_table': 'cat_hechos_violencia',
            },
        ),
        migrations.CreateModel(
            name='SectorSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sector Social',
                'verbose_name_plural': 'Sectores Sociales',
                'db_table': 'cat_sector_social',
            },
        ),
        migrations.CreateModel(
            name='SubformaAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_forma_ac', models.IntegerField(blank=True, null=True)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Subforma Acción Colectiva',
                'verbose_name_plural': 'Subformas Acciones Colectivas',
                'db_table': 'cat_subforma_ac',
            },
        ),
        migrations.CreateModel(
            name='Violencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_victimas', models.TextField(blank=True, null=True)),
                ('is_hombres', models.BooleanField(blank=True, null=True)),
                ('is_mujeres', models.BooleanField(blank=True, null=True)),
                ('is_victima_dirigente', models.BooleanField(blank=True, null=True)),
                ('responsable_estatal_desc', models.TextField(blank=True, null=True)),
                ('responsable_no_estatal_desc', models.TextField(blank=True, null=True)),
                ('condicion_mujeres_victimas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.condicionmujervictima')),
                ('forma_hecho_violencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.formahechoviolencia')),
                ('hecho_violencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.hechosviolencia')),
                ('nota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='source.nota')),
                ('opositores', models.ManyToManyField(blank=True, db_table='ocs.violencias_to_opositores', to='actor.opositor')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.proyecto')),
                ('sector_social_victima', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.sectorsocial')),
                ('temporalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space_time.temporalidad')),
                ('ubicaciones', models.ManyToManyField(blank=True, db_table='ocs.violencias_to_ubicaciones', to='space_time.ubicacion')),
            ],
            options={
                'verbose_name': 'Violencia',
                'verbose_name_plural': 'Violencias',
                'db_table': 'violencias',
            },
        ),
        migrations.CreateModel(
            name='OpositoresToAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion_colectiva', models.ForeignKey(blank=True, db_column='ac_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='event.accionescolectivas')),
                ('opositor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actor.opositor')),
            ],
            options={
                'verbose_name': 'Opositor a Acción Colectiva',
                'verbose_name_plural': 'Opositores a Acciones Colectivas',
                'db_table': 'opositores_to_ac',
            },
        ),
        migrations.CreateModel(
            name='GruposApoyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_grupo_apoyo', models.TextField(blank=True, null=True)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('interes', models.TextField(blank=True, null=True)),
                ('nota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='source.nota')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.proyecto')),
            ],
            options={
                'verbose_name': 'Grupo Apoyo',
                'verbose_name_plural': 'Grupos Apoyo',
                'db_table': 'grupos_apoyo',
            },
        ),
        migrations.AddField(
            model_name='accionescolectivas',
            name='forma_ac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.formaac'),
        ),
        migrations.AddField(
            model_name='accionescolectivas',
            name='nota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='source.nota'),
        ),
        migrations.AddField(
            model_name='accionescolectivas',
            name='opositores',
            field=models.ManyToManyField(blank=True, through='event.OpositoresToAC', to='actor.opositor'),
        ),
        migrations.AddField(
            model_name='accionescolectivas',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.proyecto'),
        ),
        migrations.AddField(
            model_name='accionescolectivas',
            name='subforma_ac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.subformaac'),
        ),
        migrations.AddField(
            model_name='accionescolectivas',
            name='temporalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space_time.temporalidad'),
        ),
        migrations.AddField(
            model_name='accionescolectivas',
            name='ubicaciones',
            field=models.ManyToManyField(blank=True, db_table='ocs.ac_to_ubicaciones', to='space_time.ubicacion'),
        ),
    ]
