# Generated by Django 4.2.9 on 2024-05-09 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_flux', '0001_initial'),
        ('actor', '0003_originreference'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('help_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rol en Evento',
                'verbose_name_plural': 'Roles en Eventos',
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.eventtype'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='status_validation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol'),
        ),
        migrations.CreateModel(
            name='Involved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_women', models.IntegerField(blank=True, null=True)),
                ('number_men', models.IntegerField(blank=True, null=True)),
                ('number_mix', models.IntegerField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('event_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.eventrole')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actor.participant')),
            ],
        ),
        migrations.CreateModel(
            name='EventSubtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('event_types', models.ManyToManyField(blank=True, to='event.eventtype')),
                ('status_validation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol')),
            ],
            options={
                'verbose_name': 'Subtipo de Evento',
                'verbose_name_plural': 'Subtipos de Eventos',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='event_subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.eventsubtype'),
        ),
    ]
