# Generated by Django 4.2.9 on 2024-05-15 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_flux', '0001_initial'),
        ('space_time', '0002_locality_state_municipality_location_and_more'),
        ('event', '0002_eventrole_alter_event_options_event_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='involved',
            options={'verbose_name': 'Involucrado en Evento', 'verbose_name_plural': 'Involucrados en Eventos'},
        ),
        migrations.CreateModel(
            name='EventLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space_time.location')),
                ('status_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol')),
            ],
            options={
                'verbose_name': 'Ubicación de Evento',
                'verbose_name_plural': 'Ubicaciones de Eventos',
            },
        ),
    ]
