# Generated by Django 4.2.9 on 2025-01-09 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='event.eventtype'),
        ),
        migrations.AlterField(
            model_name='eventsubtype',
            name='event_types',
            field=models.ManyToManyField(blank=True, related_name='event_subtypes', to='event.eventtype'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='event_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event.eventgroup'),
            preserve_default=False,
        ),
    ]
