# Generated by Django 4.2.9 on 2025-01-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='has_displacement',
            field=models.BooleanField(default=False),
        ),
    ]
