# Generated by Django 4.2.9 on 2024-09-21 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_mention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='involved',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='involvements', to='event.event'),
        ),
    ]
