# Generated by Django 4.2.9 on 2024-09-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_involved_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgroup',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
