# Generated by Django 4.2.9 on 2025-01-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_eventgroup_description_alter_event_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='number_men',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='number_mix',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='number_women',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
