# Generated by Django 4.2.9 on 2025-01-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_eventtype_has_displacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgroup',
            name='show_position',
            field=models.BooleanField(default=False),
        ),
    ]
