# Generated by Django 4.2.9 on 2024-10-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_eventgroup_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgroup',
            name='order',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='eventrole',
            name='order',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='eventsubtype',
            name='order',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='order',
            field=models.SmallIntegerField(default=20),
        ),
    ]
