# Generated by Django 4.2.9 on 2025-01-29 01:43

from django.db import migrations, models
import django.db.models.deletion


def initial_purposes(apps, schema_editor):
    # from event.models import Purpose
    Purpose = apps.get_model('event', 'Purpose')
    Purpose.objects.bulk_create([
        Purpose(name='Despojo', order=1),
        Purpose(name='Defensa', order=2),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_eventgroup_show_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.SmallIntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Propósito de Evento',
                'verbose_name_plural': 'Propósitos de Eventos',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='event.purpose'),
        ),
        migrations.RunPython(initial_purposes),
    ]
