# Generated by Django 4.2.9 on 2025-01-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_number_men_event_number_mix_event_number_women'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='has_displacement',
            field=models.BooleanField(default=False),
        ),
    ]
