# Generated by Django 4.2.9 on 2024-10-11 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_eventgroup_order_eventrole_order_eventsubtype_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventgroup',
            options={'ordering': ['order'], 'verbose_name': 'Grupo de Evento', 'verbose_name_plural': 'Grupos de Eventos'},
        ),
        migrations.AlterModelOptions(
            name='eventrole',
            options={'ordering': ['order'], 'verbose_name': 'Rol en Evento', 'verbose_name_plural': 'Roles en Eventos'},
        ),
        migrations.AlterModelOptions(
            name='eventsubtype',
            options={'ordering': ['order'], 'verbose_name': 'Subtipo de Evento', 'verbose_name_plural': 'Subtipos de Eventos'},
        ),
    ]
