# Generated by Django 4.2.9 on 2025-01-30 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_purpose_event_purpose'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtype',
            options={'ordering': ['order'], 'verbose_name': 'Tipo de Evento', 'verbose_name_plural': 'Tipos de Eventos'},
        ),
    ]
