# Generated by Django 4.2.9 on 2024-10-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_eventgroup_options_alter_eventrole_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventRole',
            new_name='InvolvedRole',
        ),
        migrations.AlterModelOptions(
            name='involvedrole',
            options={'ordering': ['order'], 'verbose_name': 'Rol en Actividad', 'verbose_name_plural': 'Roles en Actividades'},
        ),
        migrations.RenameField(
            model_name='involved',
            old_name='event_role',
            new_name='involved_role',
        ),
        migrations.AddField(
            model_name='eventgroup',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
