# Generated by Django 4.2.9 on 2025-01-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_eventtype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgroup',
            name='help_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
