# Generated by Django 4.2.9 on 2024-10-23 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_rename_eventrole_involvedrole_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventtype',
            old_name='group',
            new_name='event_group',
        ),
    ]
