# Generated by Django 4.2.9 on 2025-07-11 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0014_merge_20250218_1711'),
        ('event', '0007_eventgroup_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='event.eventtype'),
        ),
        migrations.AlterField(
            model_name='event',
            name='mention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='source.mention'),
        ),
    ]
