# Generated by Django 5.2.6 on 2025-10-30 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_alter_event_event_type_alter_event_mention'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_subtype',
        ),
    ]
