# Generated by Django 4.2.9 on 2024-10-30 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_rename_group_eventtype_event_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventlocation',
            old_name='status_register',
            new_name='status_location',
        ),
    ]
