# Generated by Django 4.2.9 on 2024-10-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_rename_status_register_eventlocation_status_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsubtype',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
