# Generated by Django 5.2.6 on 2025-11-16 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_remove_event_event_subtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='duration',
        ),
    ]
