# Generated by Django 5.2.6 on 2026-02-05 16:36

from django.db import migrations, models

def set_conflict_related(apps, schema_editor):
    EventGroup = apps.get_model('event', 'EventGroup')
    conflict_keywords = ["violencia", "colect"]
    for group in EventGroup.objects.all():
        if any(kw in group.name.lower() for kw in conflict_keywords):
            group.is_conflict_related = True
            group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_remove_event_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event_type__event_group__order', 'event_type__order', 'id'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AddField(
            model_name='eventgroup',
            name='is_conflict_related',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_conflict_related),
    ]
