# Generated by Django 5.2.6 on 2026-02-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_alter_event_options_eventgroup_is_conflict_related'),
    ]

    operations = [
        migrations.AddField(
            model_name='purpose',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
