# Generated by Django 5.2.6 on 2026-02-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_purpose_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='purpose',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
