# Generated by Django 5.2.6 on 2026-02-18 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0005_interest_interest_type'),
        ('event', '0013_purpose_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsubtype',
            name='purpose_defense',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventsubtype',
            name='purpose_spoliation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purpose',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='involved',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='involvements', to='actor.participant'),
        ),
    ]
