# Generated by Django 5.2.6 on 2026-02-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_eventsubtype_purpose_defense_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsubtype',
            name='purpose_defense',
        ),
        migrations.RemoveField(
            model_name='eventsubtype',
            name='purpose_spoliation',
        ),
        migrations.AddField(
            model_name='eventtype',
            name='purpose_defense',
            field=models.TextField(blank=True, null=True, verbose_name='Explicación del mecanismo legal de defensa'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='purpose_spoliation',
            field=models.TextField(blank=True, null=True, verbose_name='Explicación del mecanismo legal de despojo'),
        ),
    ]
