# Generated by Django 5.2.6 on 2026-02-24 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_remove_eventsubtype_purpose_defense_and_more'),
        ('work_flux', '0004_alter_statuscontrol_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='involvedrole',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='involvedrole',
            name='status_validation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol'),
        ),
        migrations.AddField(
            model_name='purpose',
            name='help_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='name',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='order',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='eventsubtype',
            name='name',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='name',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='order',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='involvedrole',
            name='name',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='name',
            field=models.CharField(max_length=160),
        ),
    ]
