# Generated by Django 5.2.6 on 2026-05-19 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_involvedrole_comments_involvedrole_status_validation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reclassification_confidence',
            field=models.SmallIntegerField(blank=True, help_text='Confianza en la reclasificación (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='reclassification_data',
            field=models.JSONField(blank=True, help_text='Snapshot original + propuesta IA, para comparar', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='reclassification_stage',
            field=models.CharField(blank=True, choices=[('pending', 'Pendiente'), ('reclassified', 'Reclasificado'), ('problematic', 'Problemático'), ('confirmed', 'Confirmado'), ('discarded', 'Descartado')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='event_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_types', to='event.eventgroup'),
        ),
    ]
