# Generated by Django 4.2.9 on 2024-04-25 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general_cats', '0001_initial'),
        ('actors', '0001_initial'),
        ('notes', '0001_initial'),
        ('projects', '0001_initial'),
        ('tempo_extend', '0001_initial'),
        ('ubication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccioneColectiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Acción Colectiva',
                'verbose_name_plural': 'Acciones Colectivas',
                'db_table': 'acciones_colectivas',
            },
        ),
        migrations.CreateModel(
            name='FormaAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Forma Acción Colectiva',
                'verbose_name_plural': 'Formas Acciones Colectivas',
                'db_table': 'cat_forma_ac',
            },
        ),
        migrations.CreateModel(
            name='FormaHechoViolencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Forma Hecho Violencia',
                'verbose_name_plural': 'Formas Hecho Violencia',
                'db_table': 'cat_forma_hecho_violencia',
            },
        ),
        migrations.CreateModel(
            name='HechosViolencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Hecho Violencia',
                'verbose_name_plural': 'Hechos Violencia',
                'db_table': 'cat_hechos_violencia',
            },
        ),
        migrations.CreateModel(
            name='SubformaAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_forma_ac', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Subforma Acción Colectiva',
                'verbose_name_plural': 'Subformas Acciones Colectivas',
                'db_table': 'cat_subforma_ac',
            },
        ),
        migrations.CreateModel(
            name='Violencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_victimas', models.TextField()),
                ('is_hombres', models.BooleanField()),
                ('is_mujeres', models.BooleanField()),
                ('is_victima_dirigente', models.BooleanField()),
                ('responsable_estatal_desc', models.TextField()),
                ('responsable_no_estatal_desc', models.TextField()),
                ('condicion_mujeres_victimas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_cats.condicionmujervictima')),
                ('forma_hecho_violencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.formahechoviolencia')),
                ('hecho_violencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.hechosviolencia')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.nota')),
                ('opositores', models.ManyToManyField(db_table='ocs.violencias_to_opositores', to='actors.opositor')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.proyecto')),
                ('sector_social_victima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_cats.sectorsocial')),
                ('temporalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tempo_extend.temporalidad')),
                ('ubicaciones', models.ManyToManyField(db_table='ocs.violencias_to_ubicaciones', to='ubication.ubicacion')),
            ],
            options={
                'verbose_name': 'Violencia',
                'verbose_name_plural': 'Violencias',
                'db_table': 'violencias',
            },
        ),
        migrations.CreateModel(
            name='OpositoresToAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accione_colectiva', models.ForeignKey(db_column='ac_id', on_delete=django.db.models.deletion.CASCADE, to='events.accionecolectiva')),
                ('opositor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors.opositor')),
            ],
            options={
                'verbose_name': 'Opositor a Acción Colectiva',
                'verbose_name_plural': 'Opositores a Acciones Colectivas',
                'db_table': 'opositores_to_ac',
            },
        ),
        migrations.CreateModel(
            name='GruposApoyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_grupo_apoyo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('interes', models.TextField()),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.nota')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.proyecto')),
            ],
            options={
                'verbose_name': 'Grupo Apoyo',
                'verbose_name_plural': 'Grupos Apoyo',
                'db_table': 'grupos_apoyo',
            },
        ),
        migrations.AddField(
            model_name='accionecolectiva',
            name='forma_ac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.formaac'),
        ),
        migrations.AddField(
            model_name='accionecolectiva',
            name='nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.nota'),
        ),
        migrations.AddField(
            model_name='accionecolectiva',
            name='opositores',
            field=models.ManyToManyField(through='events.OpositoresToAC', to='actors.opositor'),
        ),
        migrations.AddField(
            model_name='accionecolectiva',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.proyecto'),
        ),
        migrations.AddField(
            model_name='accionecolectiva',
            name='subforma_ac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.subformaac'),
        ),
        migrations.AddField(
            model_name='accionecolectiva',
            name='temporalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tempo_extend.temporalidad'),
        ),
        migrations.AddField(
            model_name='accionecolectiva',
            name='ubicaciones',
            field=models.ManyToManyField(db_table='ocs.ac_to_ubicaciones', to='ubication.ubicacion'),
        ),
    ]
