# Generated by Django 4.2.9 on 2024-04-25 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatTemporalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Temporalidad',
                'verbose_name_plural': 'Temporalidades',
                'db_table': 'cat_temporalidad',
            },
        ),
        migrations.CreateModel(
            name='Temporalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('intervalo', models.DurationField()),
                ('day_undefined', models.BooleanField(default=False)),
                ('month_undefined', models.BooleanField(default=False)),
                ('cat_temporalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tempo_extend.cattemporalidad')),
            ],
            options={
                'verbose_name': 'Temporalidad',
                'verbose_name_plural': 'Temporalidades',
                'db_table': 'temporalidad',
            },
        ),
    ]
