# Generated by Django 4.2.9 on 2025-01-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccionColectivaToUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Acción Colectiva a Ubicación',
                'verbose_name_plural': 'Acciones Colectivas a Ubicaciones',
                'db_table': 'ac_to_ubicaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccionesColectivas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Acción Colectiva',
                'verbose_name_plural': 'Acciones Colectivas',
                'db_table': 'acciones_colectivas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AfectacionEcologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_ae', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Afectación Ecológica',
                'verbose_name_plural': 'Afectaciones Ecológicas',
                'db_table': 'afectaciones_ecologicas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AfectacionEcologicaToUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Afectación Ecológica a Ubicación',
                'verbose_name_plural': 'Afectaciones Ecológicas a Ubicaciones',
                'db_table': 'ae_to_ubicaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AfectacionSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_as', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Afectación Social',
                'verbose_name_plural': 'Afectaciones Sociales',
                'db_table': 'afectaciones_sociales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AfectacionSocialToUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Afectación Social a Ubicación',
                'verbose_name_plural': 'Afectaciones Sociales a Ubicaciones',
                'db_table': 'as_to_ubicaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, null=True)),
                ('matriz', models.TextField(blank=True, null=True)),
                ('filial', models.TextField(blank=True, null=True)),
                ('directores', models.TextField(blank=True, null=True)),
                ('inversionistas', models.TextField(blank=True, null=True)),
                ('nacionalidad', models.TextField(blank=True, null=True)),
                ('is_capital_publico', models.BooleanField(blank=True, null=True)),
                ('is_cotiza_bolsa', models.BooleanField(blank=True, null=True)),
                ('interes', models.TextField(blank=True, null=True)),
                ('is_activo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Capital',
                'verbose_name_plural': 'Capitales',
                'db_table': 'capital',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatPoblacionAfectada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cat Población Afectada',
                'verbose_name_plural': 'Cat Poblaciones Afectadas',
                'db_table': 'cat_poblacion_afectada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatSubpoblacionAfectada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_subpoblacion_af', models.IntegerField(blank=True, null=True)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cat Subpoblación Afectada',
                'verbose_name_plural': 'Cat Subpoblaciones Afectadas',
                'db_table': 'cat_subpoblacion_afectada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatTemporalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cat Temporalidad',
                'verbose_name_plural': 'Cat Temporalidades',
                'db_table': 'cat_temporalidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CondicionMujerVictima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Condición Mujer Víctima',
                'verbose_name_plural': 'Condiciones Mujer Víctima',
                'db_table': 'cat_condicion_mujer_victima',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CSA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'CSA',
                'verbose_name_plural': 'CSAs',
                'db_table': 'csa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituciones_a_favor_proyecto', models.TextField(blank=True, null=True)),
                ('instituciones_mediadoras', models.TextField(blank=True, null=True)),
                ('instituciones_atienden_reclamos', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstatusProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Estatus Proyecto',
                'verbose_name_plural': 'Estatus Proyectos',
                'db_table': 'cat_estatus_proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstatusProyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Estatus Proyecto',
                'verbose_name_plural': 'Estatus Proyectos',
                'db_table': 'estatus_proyectos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FormaAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Forma Acción Colectiva',
                'verbose_name_plural': 'Formas Acciones Colectivas',
                'db_table': 'cat_forma_ac',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FormaHechoViolencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Forma Hecho Violencia',
                'verbose_name_plural': 'Formas Hecho Violencia',
                'db_table': 'cat_forma_hecho_violencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FormaOrganizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Forma Organización',
                'verbose_name_plural': 'Formas Organización',
                'db_table': 'cat_forma_organizacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GruposApoyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_grupo_apoyo', models.TextField(blank=True, null=True)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('interes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Grupo Apoyo',
                'verbose_name_plural': 'Grupos Apoyo',
                'db_table': 'grupos_apoyo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HechosViolencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hecho Violencia',
                'verbose_name_plural': 'Hechos Violencia',
                'db_table': 'cat_hechos_violencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InteresesOpositores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Interés Opositor',
                'verbose_name_plural': 'Intereses Opositores',
                'db_table': 'intereses_opositores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InteresesPoblacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Interés Población',
                'verbose_name_plural': 'Intereses Poblaciones',
                'db_table': 'intereses_poblacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mujer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mujer',
                'verbose_name_plural': 'Mujeres',
                'db_table': 'cat_mujer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_nota', models.IntegerField(blank=True, null=True)),
                ('titulo', models.TextField(blank=True, null=True)),
                ('autor', models.TextField(blank=True, null=True)),
                ('nombre_medio', models.TextField(blank=True, null=True)),
                ('pagina_medio', models.TextField(blank=True, null=True)),
                ('vinculo', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('fecha_captura', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'db_table': 'notas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Opositores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, null=True)),
                ('is_campesino_or_comunero_or_ejidatario', models.BooleanField(blank=True, null=True)),
                ('is_trabajador_empresa', models.BooleanField(blank=True, null=True)),
                ('is_habitante_zona', models.BooleanField(blank=True, null=True)),
                ('is_indigena', models.BooleanField(blank=True, null=True)),
                ('pueblo_indigena', models.TextField(blank=True, null=True)),
                ('otros_opositores', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Opositor',
                'verbose_name_plural': 'Opositores',
                'db_table': 'opositores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpositoresToAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Opositor a Acción Colectiva',
                'verbose_name_plural': 'Opositores a Acciones Colectivas',
                'db_table': 'opositores_to_ac',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpositorToNotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Opositor a Nota',
                'verbose_name_plural': 'Opositores a Notas',
                'db_table': 'opositores_to_notas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpositorToProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Opositor a Proyecto',
                'verbose_name_plural': 'Opositores a Proyectos',
                'db_table': 'opositores_to_proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpositorToUbicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Opositor a Ubicación',
                'verbose_name_plural': 'Opositores a Ubicaciones',
                'db_table': 'opositores_to_ubicaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Otros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_propiedad', models.TextField(blank=True, null=True)),
                ('fortalecimiento_tejido_social', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Otro',
                'verbose_name_plural': 'Otros',
                'db_table': 'otros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PoblacionAfectada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('interes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Población Afectada',
                'verbose_name_plural': 'Poblaciones Afectadas',
                'db_table': 'poblaciones_afectadas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mp', models.IntegerField(blank=True, null=True)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('escala', models.TextField(blank=True, null=True)),
                ('especificaciones', models.TextField(blank=True, null=True)),
                ('old_ubis', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'proyectos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProyectoToUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Proyecto a Ubicación',
                'verbose_name_plural': 'Proyectos a Ubicaciones',
                'db_table': 'proyectos_to_ubicaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroNotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.TextField(blank=True, null=True)),
                ('datum', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='inprogress', max_length=100, null=True)),
                ('last_edit', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Registro Nota',
                'verbose_name_plural': 'Registros Notas',
                'db_table': 'registro_notas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SectorSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sector Social',
                'verbose_name_plural': 'Sectores Sociales',
                'db_table': 'cat_sector_social',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubformaAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_forma_ac', models.IntegerField(blank=True, null=True)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Subforma Acción Colectiva',
                'verbose_name_plural': 'Subformas Acciones Colectivas',
                'db_table': 'cat_subforma_ac',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Temporalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('intervalo', models.DurationField(blank=True, null=True)),
                ('day_undefined', models.BooleanField(blank=True, default=False, null=True)),
                ('month_undefined', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'Temporalidad',
                'verbose_name_plural': 'Temporalidades',
                'db_table': 'temporalidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoAfectacionEcologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo Afectación Ecológica',
                'verbose_name_plural': 'Tipos Afectaciones Ecológicas',
                'db_table': 'cat_tipo_afectaciones_ecologicas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoAfectacionSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo Afectación Social',
                'verbose_name_plural': 'Tipos Afectaciones Sociales',
                'db_table': 'cat_tipo_afectaciones_sociales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDespliegueCapital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('icono', models.TextField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo Despliegue Capital',
                'verbose_name_plural': 'Tipos Despliegue Capital',
                'db_table': 'cat_tipo_despliegue_capital',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoMegaproyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo Megaproyecto',
                'verbose_name_plural': 'Tipos Megaproyecto',
                'db_table': 'cat_tipo_megaproyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ubicacion', models.CharField(blank=True, default='punto', max_length=100, null=True)),
                ('estado', models.TextField(blank=True, null=True)),
                ('municipio', models.TextField(blank=True, null=True)),
                ('localidad', models.TextField(blank=True, null=True)),
                ('especificaciones', models.TextField(blank=True, null=True)),
                ('sitio', models.TextField(blank=True, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'db_table': 'ubicaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Violencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_victimas', models.TextField(blank=True, null=True)),
                ('is_hombres', models.BooleanField(blank=True, null=True)),
                ('is_mujeres', models.BooleanField(blank=True, null=True)),
                ('is_victima_dirigente', models.BooleanField(blank=True, null=True)),
                ('responsable_estatal_desc', models.TextField(blank=True, null=True)),
                ('responsable_no_estatal_desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Violencia',
                'verbose_name_plural': 'Violencias',
                'db_table': 'violencias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViolenciaToOpositor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Violencia a Opositor',
                'verbose_name_plural': 'Violencias a Opositores',
                'db_table': 'violencias_to_opositores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViolenciaToUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Violencia a Ubicación',
                'verbose_name_plural': 'Violencias a Ubicaciones',
                'db_table': 'violencias_to_ubicaciones',
                'managed': False,
            },
        ),
    ]
