# Generated by Django 4.2.9 on 2024-05-16 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('space_time', '0001_initial'),
        ('work_flux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Conflicto Socioambiental',
                'verbose_name_plural': 'Conflictos Socioambientales',
            },
        ),
        migrations.CreateModel(
            name='DeploymentCapitalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='icons/')),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Tipo Despliegue Capital',
                'verbose_name_plural': 'Tipos Despliegue Capital',
            },
        ),
        migrations.CreateModel(
            name='MegaprojectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('has_many_dct', models.BooleanField(default=False, verbose_name='Difiere en Tipo de Despliegue Capital')),
                ('comments', models.TextField(blank=True, null=True)),
                ('deployment_capital_types', models.ManyToManyField(blank=True, to='project.deploymentcapitaltype')),
                ('status_validation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol')),
            ],
            options={
                'verbose_name': 'Tipo de Megaproyecto',
                'verbose_name_plural': 'Tipos de Megaproyecto',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto_id_ref', models.IntegerField(blank=True, null=True)),
                ('legacy_id_mp', models.IntegerField(blank=True, null=True)),
                ('official_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre oficial')),
                ('common_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre común')),
                ('alternative_name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('conflict', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.conflict')),
                ('megaproject_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.megaprojecttype')),
                ('parent_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='Proyecto en el que se agrupa')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('help_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Escala de los proyectos',
                'verbose_name_plural': 'Escalas de los proyectos',
            },
        ),
        migrations.CreateModel(
            name='ProjectLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space_time.location')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('status_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol')),
            ],
            options={
                'verbose_name': 'Ubicación de proyecto',
                'verbose_name_plural': 'Ubicaciones de proyectos',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.scale'),
        ),
        migrations.AddField(
            model_name='project',
            name='status_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space_time.statusproject'),
        ),
        migrations.AddField(
            model_name='project',
            name='status_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol'),
        ),
    ]
