# Generated by Django 4.2.9 on 2024-11-06 09:17

from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('space_time', '0001_initial'),
        ('work_flux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('status_validation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol')),
            ],
            options={
                'verbose_name': 'Conflicto Socioambiental',
                'verbose_name_plural': 'Conflictos Socioambientales',
            },
        ),
        migrations.CreateModel(
            name='ExtractivismType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='icons/')),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.SmallIntegerField(default=5)),
            ],
            options={
                'verbose_name': 'Tipo de Extractivismo',
                'verbose_name_plural': 'Tipos de Extractivismo',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MegaprojectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('has_many_dct', models.BooleanField(default=False, verbose_name='Difiere en Tipo de Despliegue Capital')),
                ('comments', models.TextField(blank=True, null=True)),
                ('order', models.SmallIntegerField(default=10)),
                ('extractivism_types', models.ManyToManyField(blank=True, related_name='megaproject_types', to='project.extractivismtype')),
                ('status_validation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol')),
            ],
            options={
                'verbose_name': 'Tipo de Megaproyecto',
                'verbose_name_plural': 'Tipos de Megaproyecto',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto_id_ref', models.IntegerField(blank=True, null=True)),
                ('legacy_id_mp', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre común')),
                ('official_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre oficial')),
                ('alternative_name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_grouper', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('conflict', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.conflict')),
                ('megaproject_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='project.megaprojecttype')),
                ('others_parents', models.ManyToManyField(blank=True, to='project.project', verbose_name='Otros proyectos en los que se agrupa')),
                ('parent_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='Proyecto en el que se agrupa')),
                ('status_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_location', to='work_flux.statuscontrol')),
                ('status_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='space_time.statusproject')),
                ('status_validation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_register', to='work_flux.statuscontrol')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='ProjectLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='space_time.location')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='project.project')),
                ('status_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol')),
            ],
            options={
                'verbose_name': 'Ubicación de proyecto',
                'verbose_name_plural': 'Ubicaciones de proyectos',
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=project.models.upload_to_project_file)),
                ('old_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='project.project')),
            ],
            options={
                'verbose_name': 'Archivo de proyecto',
                'verbose_name_plural': 'Archivos de proyecto',
            },
        ),
    ]
