# Generated by Django 4.2.9 on 2024-04-29 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('space_time', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Conflict',
                'verbose_name_plural': 'Conflicts',
                'db_table': 'conflicts',
            },
        ),
        migrations.CreateModel(
            name='DeploymentCapitalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Tipo Despliegue Capital',
                'verbose_name_plural': 'Tipos Despliegue Capital',
            },
        ),
        migrations.CreateModel(
            name='MegaprojectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('interests', models.JSONField(blank=True, null=True, verbose_name='Intereses (final)')),
                ('deployment_capital_types', models.ManyToManyField(blank=True, to='project.deploymentcapitaltype')),
            ],
            options={
                'verbose_name': 'Tipo de Megaproyecto',
                'verbose_name_plural': 'Tipos de Megaproyecto',
            },
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('help_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Escala de los proyectos',
                'verbose_name_plural': 'Escalas de los proyectos',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre oficial')),
                ('common_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre común')),
                ('alternative_name', models.TextField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('conflict', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.conflict')),
                ('megaproject_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.megaprojecttype')),
                ('parent_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='Proyecto en el que se agrupa')),
                ('scale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.scale')),
                ('status_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space_time.statusproject')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'projects',
            },
        ),
    ]
