# Generated by Django 4.2.9 on 2024-12-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='megaprojecttype',
            name='has_many_dct',
            field=models.BooleanField(default=False, verbose_name='Difiere en Tipo de Extractivismo'),
        ),
    ]
