# Generated by Django 4.2.9 on 2024-04-30 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_flux', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conflict',
            options={'verbose_name': 'Conflicto Socioambiental', 'verbose_name_plural': 'Conflictos Socioambientales'},
        ),
        migrations.RemoveField(
            model_name='megaprojecttype',
            name='interests',
        ),
        migrations.AddField(
            model_name='deploymentcapitaltype',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='megaprojecttype',
            name='has_many_dct',
            field=models.BooleanField(default=False, verbose_name='Difiere en Tipo de Despliegue Capital'),
        ),
        migrations.AddField(
            model_name='megaprojecttype',
            name='status_validation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol'),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='proyecto_id_ref',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol'),
        ),
        migrations.AlterModelTable(
            name='conflict',
            table=None,
        ),
        migrations.AlterModelTable(
            name='project',
            table=None,
        ),
    ]
