# Generated by Django 4.2.9 on 2025-01-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='others_parents',
            field=models.ManyToManyField(blank=True, related_name='others_children_projects', to='project.project', verbose_name='Otros proyectos en los que se agrupa'),
        ),
    ]
