# Generated by Django 4.2.9 on 2024-11-26 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_flux', '0002_alter_statuscontrol_group'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.SmallIntegerField(default=5)),
                ('comments', models.TextField(blank=True, null=True)),
                ('status_validation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol')),
            ],
            options={
                'verbose_name': 'Status Project',
                'verbose_name_plural': 'Status Projects',
                'db_table': 'space_time_statusproject',
                'ordering': ['order', 'name'],
            },
        )
    ]
