# Generated by Django 4.2.9 on 2024-11-26 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_statusproject_alter_project_status_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='project.statusproject'),
        ),
    ]
