# Generated by Django 4.2.9 on 2025-01-14 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_megaprojecttype_has_many_dct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='official_name',
        ),
    ]
