# Generated by Django 4.2.9 on 2025-07-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_others_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractivismtype',
            name='ai_name',
            field=models.CharField(blank=True, help_text='Nombre para IA, si es diferente al nombre', max_length=255, null=True),
        ),
    ]
