# Generated by Django 4.2.9 on 2024-04-30 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_conflict_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='legacy_id_mp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='alternative_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='parent_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='Proyecto en el que se agrupa'),
        ),
    ]
