# Generated by Django 4.2.9 on 2024-09-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_projectlocation_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='others_parents',
            field=models.ManyToManyField(blank=True, to='project.project', verbose_name='Otros proyectos en los que se agrupa'),
        ),
    ]
