# Generated by Django 4.2.9 on 2025-01-18 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_project_official_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='parent_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_projects', to='project.project', verbose_name='Proyecto en el que se agrupa'),
        ),
    ]
