# Generated by Django 5.2.6 on 2025-10-28 19:56

from django.db import migrations, models


def insert_short_names(apps, schema_editor):
    ExtractivismType = apps.get_model('project', 'ExtractivismType')
    extractivism_types = ExtractivismType.objects.all()
    ## ULTRA SHORT NAMES MAPPING:
    # agro = "agro"
    # mineria = "mineria"
    # hidricos = "hidricos"
    # energia = "energia"
    # urbano = "urbano"
    # infra = "infra"

    ## LARGE NAMES:
    # "Extractivismo agroindustrial, de monocultivo, industria ganadera, explotación forestal y recursos bióticos",
    # "Extractivismo minero",
    # "Extractivismo hídrico",
    # "Extractivismo energético",
    # "Hiperurbanización",
    # "Megainfraestructura y vías de comunicación",

    # FINAL SHORT NAME MAPPING:
    short_name_mappings = {
        "agro": "Agroindustrial",
        "mineria": "Minero",
        "hidricos": "Hídrico",
        "energia": "Energético",
        "urbano": "Hiperurbanización",
        "infra": "Megainfraestructura",
    }

    for et in extractivism_types:
        if not et.ai_name:
            continue
        key = et.ai_name.lower().split()[0]  # Get the first word in lowercase
        if key in short_name_mappings:
            et.short_name = short_name_mappings[key]
            et.save()


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_extractivismtype_ai_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractivismtype',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunPython(insert_short_names),
    ]
