# Generated by Django 4.2.9 on 2024-04-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_legacy_id_mp_alter_project_alternative_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploymentcapitaltype',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='megaprojecttype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
