# Generated by Django 4.2.9 on 2024-09-23 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_flux', '0001_initial'),
        ('project', '0003_project_others_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_location', to='work_flux.statuscontrol'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_register', to='work_flux.statuscontrol'),
        ),
    ]
