# Generated by Django 4.2.9 on 2025-01-20 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_parent_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='conflict',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='project.conflict'),
        ),
    ]
