# Generated by Django 4.2.9 on 2024-10-01 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_status_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='megaprojecttype',
            old_name='deployment_capital_types',
            new_name='extractivism_types',
        ),
    ]
