# Generated by Django 4.2.9 on 2024-10-01 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_rename_deployment_capital_types_megaprojecttype_extractivism_types'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeploymentCapitalType',
            new_name='ExtractivismType',
        ),
    ]
