# Generated by Django 5.2.6 on 2026-02-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project_editors'),
    ]

    operations = [
        migrations.AddField(
            model_name='megaprojecttype',
            name='help_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statusproject',
            name='help_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extractivismtype',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='extractivismtype',
            name='order',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='megaprojecttype',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='statusproject',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='statusproject',
            name='order',
            field=models.SmallIntegerField(default=10),
        ),
    ]
