# Generated by Django 5.2.6 on 2026-05-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_megaprojecttype_help_text_statusproject_help_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractivismtype',
            name='name',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='megaprojecttype',
            name='name',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='statusproject',
            name='name',
            field=models.CharField(max_length=160),
        ),
    ]
