# Generated by Django 4.2.9 on 2024-10-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_rename_deploymentcapitaltype_extractivismtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractivismtype',
            name='order',
            field=models.SmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='megaprojecttype',
            name='order',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='scale',
            name='order',
            field=models.SmallIntegerField(default=5),
        ),
    ]
