# Generated by Django 4.2.9 on 2024-10-11 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_extractivismtype_order_megaprojecttype_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extractivismtype',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Tipo Despliegue Capital', 'verbose_name_plural': 'Tipos Despliegue Capital'},
        ),
        migrations.AlterModelOptions(
            name='megaprojecttype',
            options={'ordering': ['order'], 'verbose_name': 'Tipo de Megaproyecto', 'verbose_name_plural': 'Tipos de Megaproyecto'},
        ),
        migrations.AlterModelOptions(
            name='scale',
            options={'ordering': ['order'], 'verbose_name': 'Escala de los proyectos', 'verbose_name_plural': 'Escalas de los proyectos'},
        ),
        migrations.AlterField(
            model_name='project',
            name='megaproject_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='project.megaprojecttype'),
        ),
    ]
