# Generated by Django 5.2.15 on 2026-06-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_extractivismtype_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='incongruent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='prev_status_loc',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
