# Generated by Django 4.2.9 on 2024-10-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_extractivismtype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extractivismtype',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Tipo de Extractivismo', 'verbose_name_plural': 'Tipos de Extractivismo'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='scale',
        ),
        migrations.AddField(
            model_name='project',
            name='is_grouper',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Scale',
        ),
    ]
