# Generated by Django 5.2.15 on 2026-07-21 20:05

import core.storages
import project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_project_incongruent_project_prev_status_loc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusproject',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Estatus del Proyecto', 'verbose_name_plural': 'Estatus de proyectos'},
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=models.FileField(max_length=255, storage=core.storages.select_docs_storage, upload_to=project.models.upload_to_project_file),
        ),
    ]
