# Generated by Django 5.2.17 on 2026-08-24 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_statusproject_options_alter_projectfile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='incongruent',
        ),
        migrations.RemoveField(
            model_name='project',
            name='prev_status_loc',
        ),
    ]
