# Generated by Django 4.2.9 on 2024-10-24 10:14

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_projectfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=models.FileField(upload_to=project.models.upload_to_project_file),
        ),
    ]
