# Generated by Django 4.2.9 on 2024-10-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_alter_projectfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='megaprojecttype',
            name='extractivism_types',
            field=models.ManyToManyField(blank=True, related_name='megaproject_types', to='project.extractivismtype'),
        ),
    ]
