# Generated by Django 4.2.9 on 2024-10-30 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space_time', '0006_alter_statusproject_options'),
        ('project', '0013_alter_megaprojecttype_extractivism_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='status_register',
            new_name='status_validation',
        ),
        migrations.RenameField(
            model_name='projectlocation',
            old_name='status_register',
            new_name='status_location',
        ),
        migrations.AlterField(
            model_name='project',
            name='status_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='space_time.statusproject'),
        ),
    ]
