# Generated by Django 4.2.9 on 2024-10-30 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_flux', '0002_statuscontrol_is_public'),
        ('project', '0014_rename_status_register_project_status_validation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conflict',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conflict',
            name='status_validation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol'),
        ),
    ]
