# Generated by Django 4.2.9 on 2024-11-05 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_conflict_comments_conflict_status_validation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='official_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='common_name',
        ),
    ]
