# Generated by Django 4.2.9 on 2024-11-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_rename_official_name_project_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='official_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre oficial'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre común'),
        ),
    ]
