# Generated by Django 4.2.9 on 2024-11-06 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work_flux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('is_social', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Grupo de Impacto',
                'verbose_name_plural': 'Grupos de Impactos',
            },
        ),
        migrations.CreateModel(
            name='ImpactType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('has_subtype', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('short_name', models.CharField(blank=True, help_text='Nombre corto', max_length=50, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('order', models.SmallIntegerField(default=0)),
                ('impact_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='impact.impactgroup')),
                ('status_validation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol')),
            ],
            options={
                'verbose_name': 'Tipo de Impacto',
                'verbose_name_plural': 'Tipos de Impactos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ImpactSubtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('order', models.SmallIntegerField(default=0)),
                ('impact_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='impact.impacttype')),
                ('status_validation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol')),
            ],
            options={
                'verbose_name': 'Subtipo de Impacto',
                'verbose_name_plural': 'Subtipos de Impactos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_potential', models.BooleanField(blank=True, null=True)),
                ('impact_subtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='impact.impactsubtype')),
                ('impact_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='impact.impacttype')),
            ],
            options={
                'verbose_name': 'Impacto',
                'verbose_name_plural': 'Impactos',
            },
        ),
    ]
