# Generated by Django 4.2.9 on 2024-04-26 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('source', '__first__'),
        ('project', '__first__'),
        ('space_time', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAfectacionesEcologicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo Afectación Ecológica',
                'verbose_name_plural': 'Tipos Afectaciones Ecológicas',
                'db_table': 'cat_tipo_afectaciones_ecologicas',
            },
        ),
        migrations.CreateModel(
            name='TipoAfectacionesSociales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo Afectación Social',
                'verbose_name_plural': 'Tipos Afectaciones Sociales',
                'db_table': 'cat_tipo_afectaciones_sociales',
            },
        ),
        migrations.CreateModel(
            name='Otros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_propiedad', models.TextField(blank=True, null=True)),
                ('fortalecimiento_tejido_social', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='source.nota')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.proyecto')),
            ],
            options={
                'verbose_name': 'Otro',
                'verbose_name_plural': 'Otros',
                'db_table': 'otros',
            },
        ),
        migrations.CreateModel(
            name='AfectacionesSociales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_as', models.TextField(blank=True, null=True)),
                ('nota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='source.nota')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.proyecto')),
                ('temporalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space_time.temporalidad')),
                ('tipo_as', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='impact.tipoafectacionessociales')),
                ('ubicaciones', models.ManyToManyField(blank=True, db_table='ocs.as_to_ubicaciones', to='space_time.ubicacion')),
            ],
            options={
                'verbose_name': 'Afectación Social',
                'verbose_name_plural': 'Afectaciones Sociales',
                'db_table': 'afectaciones_sociales',
            },
        ),
        migrations.CreateModel(
            name='AfectacionesEcologicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_ae', models.TextField(blank=True, null=True)),
                ('nota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='source.nota')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.proyecto')),
                ('temporalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space_time.temporalidad')),
                ('tipo_ae', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='impact.tipoafectacionesecologicas')),
                ('ubicaciones', models.ManyToManyField(blank=True, db_table='ocs.ae_to_ubicaciones', to='space_time.ubicacion')),
            ],
            options={
                'verbose_name': 'Afectación Ecológica',
                'verbose_name_plural': 'Afectaciones Ecológicas',
                'db_table': 'afectaciones_ecologicas',
            },
        ),
    ]
