# Generated by Django 4.2.9 on 2024-06-28 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
        ('impact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impact',
            name='mention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='source.mention'),
        ),
    ]
