# Generated by Django 4.2.9 on 2025-01-02 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impacttype',
            name='has_subtype',
        ),
    ]
