# Generated by Django 4.2.9 on 2024-11-26 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impactsubtype',
            name='impact_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_subtypes', to='impact.impacttype'),
        ),
    ]
