# Generated by Django 4.2.9 on 2025-01-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impact',
            options={'verbose_name': 'Afectación', 'verbose_name_plural': 'Afectaciones'},
        ),
        migrations.AlterModelOptions(
            name='impactgroup',
            options={'verbose_name': 'Grupo de Afectaciones', 'verbose_name_plural': 'Grupos de Afectaciones'},
        ),
        migrations.AlterModelOptions(
            name='impactsubtype',
            options={'ordering': ['order'], 'verbose_name': 'Subtipo de Afectación', 'verbose_name_plural': 'Subtipos de Afectaciones'},
        ),
        migrations.AlterModelOptions(
            name='impacttype',
            options={'ordering': ['order'], 'verbose_name': 'Tipo de Afectación', 'verbose_name_plural': 'Tipos de Afectaciones'},
        ),
        migrations.AddField(
            model_name='impactgroup',
            name='show_position',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='impacttype',
            name='has_displacement',
            field=models.BooleanField(default=False),
        ),
    ]
