# Generated by Django 4.2.9 on 2024-09-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0002_alter_impact_mention'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impact',
            options={'verbose_name': 'Impacto', 'verbose_name_plural': 'Impactos'},
        ),
        migrations.AddField(
            model_name='impacttype',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='impacttype',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
