# Generated by Django 4.2.9 on 2024-10-01 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_flux', '0001_initial'),
        ('impact', '0003_alter_impact_options_impacttype_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactsubtype',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='impactsubtype',
            name='status_validation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol'),
        ),
        migrations.AlterField(
            model_name='impacttype',
            name='short_name',
            field=models.CharField(blank=True, help_text='Nombre corto', max_length=50, null=True),
        ),
    ]
