# Generated by Django 4.2.9 on 2025-01-08 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0003_remove_impacttype_has_subtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impacttype',
            name='impact_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='impact.impactgroup'),
            preserve_default=False,
        ),
    ]
