# Generated by Django 4.2.9 on 2025-01-28 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0003_alter_impact_options_alter_impactgroup_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impactgroup',
            name='show_position',
        ),
    ]
