# Generated by Django 4.2.9 on 2024-10-11 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0004_impactsubtype_order_impactsubtype_status_validation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('is_social', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Grupo de Impacto',
                'verbose_name_plural': 'Grupos de Impactos',
            },
        ),
        migrations.AlterModelOptions(
            name='impactsubtype',
            options={'ordering': ['order'], 'verbose_name': 'Subtipo de Impacto', 'verbose_name_plural': 'Subtipos de Impactos'},
        ),
        migrations.AlterModelOptions(
            name='impacttype',
            options={'ordering': ['order'], 'verbose_name': 'Tipo de Impacto', 'verbose_name_plural': 'Tipos de Impactos'},
        ),
        migrations.RemoveField(
            model_name='impacttype',
            name='is_social',
        ),
        migrations.AddField(
            model_name='impacttype',
            name='impact_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='impact.impactgroup'),
        ),
    ]
