# Generated by Django 4.2.9 on 2025-01-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0004_remove_impactgroup_show_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactgroup',
            name='help_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
