# Generated by Django 4.2.9 on 2025-01-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0004_alter_impacttype_impact_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactgroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
