# Generated by Django 4.2.9 on 2024-10-20 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_flux', '0002_statuscontrol_is_public'),
        ('impact', '0005_impactgroup_alter_impactsubtype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='impacttype',
            name='status_validation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_flux.statuscontrol'),
        ),
    ]
