# Generated by Django 4.2.9 on 2024-10-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0006_impacttype_status_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactsubtype',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='impacttype',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
